### PR TITLE
better handling for containerd error message

### LINKED ISSUE #6587: Testing of graceful stop for containerd fails intermittently
## Summary

`TestGracefulStop` from the containerd integration test suite fails intermittently. When we last investigated this the failure was hard to reproduce locally, and was not reproducible consistently. At the time we chalked it up to a race condition in the test setup.

However, it would be useful to do some further investigation into the [process killing mechanism](https://github.com/concourse/concourse/blob/96dd07ee40ec1364dd1839bbb0dc717eaa100818/worker/runtime/process_killer.go#L76).

Example failed [build](https://ci.concourse-ci.org/teams/contributor/pipelines/prs/jobs/containerd-integration/builds/156?vars.branch=%22master%22)

## Steps to reproduce

The failure can't be produced consistently at the moment. Assuming you're in the `concourse` repository.
```
docker run --privileged -v (pwd):/concourse -w /concourse -it --entrypoint /bin/bash concourse/dev
cd worker/runtime/integration
go test . -v
```

To run only the graceful stop test:
```
go test -run TestSuite/TestGracefulStop -v
```

## Expected results
All tests pass.

## Actual results

```
== RUN   TestSuite/TestCustomDNS

=== RUN   TestSuite/TestGracefulStop

=== CONT  TestSuite

    integration_test.go:544: 

        	Error Trace:	integration_test.go:544

        	            				integration_test.go:517

        	Error:      	Received unexpected error:

        	            	kill: graceful kill: kill task execed processes: kill procs: proc kill: waiting for exit status: rpc error: code = Unknown desc = context deadline exceeded: unknown

        	Test:       	TestSuite

    integration_test.go:530: 

        	Error Trace:	integration_test.go:530

        	            				panic.go:632

        	            				testing.go:742

        	            				integration_test.go:544

        	            				integration_test.go:517

        	Error:      	Received unexpected error:

        	            	gracefully killing task: graceful kill: kill task execed processes: kill procs: proc kill: waiting for exit status: rpc error: code = Unknown desc = context deadline exceeded: unknown

        	Test:       	TestSuite

=== CONT  TestSuite/TestGracefulStop

    testing.go:1104: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test

--- FAIL: TestSuite (52.25s)

    --- PASS: TestSuite/TestAttach (15.43s)

    --- PASS: TestSuite/TestAttachToUnknownProc (2.51s)

    --- PASS: TestSuite/TestContainerCreateRunStopedDestroy (2.57s)

    --- PASS: TestSuite/TestContainerNetworkEgress (2.46s)

    --- PASS: TestSuite/TestContainerNetworkEgressWithRestrictedNetworks (3.56s)

    --- PASS: TestSuite/TestCustomDNS (2.71s)

    --- FAIL: TestSuite/TestGracefulStop (22.28s)

FAIL

FAIL	github.com/concourse/concourse/worker/runtime/integration	52.488s

```

## Additional context

The test cache will have to be cleaned using `go clean -testcache` if you're trying to reproduce simply by rerunning.

## Triaging info

* Concourse version: v7.0 (and several versions prior)
* Browser (if applicable):
* Did this used to work? No

### PR DESCRIPTION
**Pull request by muntac**
[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix

When killing a process gracefully containerd might exceed the waitperiod. When this happens it returns an error in a format that couldn't be handled properly. We now look at the specific grpc code for better handling.

Signed-off-by: Bohan Chen <bochen@pivotal.io>
Co-authored-by: Muntasir Chowdhury <mchowdhury@pivotal.io>

closes #6587.

## Notes to reviewer:

```diff
diff --git a/worker/runtime/process_killer.go b/worker/runtime/process_killer.go
index 5dc61a2e4..668752f82 100644
--- a/worker/runtime/process_killer.go
+++ b/worker/runtime/process_killer.go
@@ -54,7 +54,10 @@ func (p processKiller) Kill(
        waitCtx, cancel := context.WithTimeout(ctx, waitPeriod)
        defer cancel()

-       statusC, err := proc.Wait(waitCtx)
+       waitCtx2, cancel2 := context.WithTimeout(ctx, waitPeriod - (10 * time.Millisecond))
+       defer cancel2()
+       statusC, err := proc.Wait(waitCtx2)
+
        if err != nil {
                return fmt.Errorf("proc wait: %w", err)
        }
```

To recreate the error described in #6587 all you need adjust the timing so that the `proc.Wait()` expires before the `waitCtx`. To validate that the error is now handled correctly do this both in the original code and the PR branch. The latter should pass.

## Release Note

* Fixed a bug with the `containerd` runtime where gracefully stopping a container might have failed with an unhandled error. Now it gracefully shuts down.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

File: worker/runtime/process_killer.go [hunk 1]
```diff
@@ -70,10 +74,18 @@ func (p processKiller) Kill(
 		}
 
 		return fmt.Errorf("waitctx done: %w", err)
-	case status := <-statusC:
-		err = status.Error()
+	case exitStatus := <-procWaitStatus:
+		err = exitStatus.Error()
 		if err != nil {
-			return fmt.Errorf("waiting for exit status: %w", err)
+			grpcErr := status.Convert(err)
```
Comment (aoldershaw) [inline worker/runtime/process_killer.go:80]: Is it possible for `err` to not be a gRPC error? Should we use `grpcErr, ok := status.FromError(err)` instead and handle the case where `!ok`?

Comment (muntac) [reply worker/runtime/process_killer.go:80]: @aoldershaw When `ok` is `false` the `FromError()` returns a `Status` with `codes.Unknown`. So the `DeadlineExceeded` condition will get skipped and the original `err` object will get returned.

Comment (aoldershaw) [reply worker/runtime/process_killer.go:80]: makes sense, thanks for the explanation!

**Review by aoldershaw — APPROVED** [review]
