### PR TITLE
Cache Vault KV version by mount path to reduce preflight calls (`CONCOURSE_VAULT_ENABLE_KV_MOUNT_CACHE`)

### LINKED ISSUE #9514: Vault secret read makes two Vault API calls per secret (KV version preflight + secret read)
### Summary

Concourse currently performs a [KV](https://developer.hashicorp.com/vault/docs/secrets/kv) version preflight request for every secret read, followed by the actual secret read. This results in two Vault API calls per secret lookup.

In large Concourse deployments - especially those with many pipelines and resources using Vault as a credential manager - this behavior can significantly increase request volume and may lead to Vault rate limiting (requests-per-second limits being exceeded).

### Code evidence:

- In [api_client.go:66](https://github.com/concourse/concourse/blob/d0130396c1cb50c6d114bd55317ffa2d121d7b29/atc/creds/vault/api_client.go#L66), Read calls isKVv2 before reading the secret.
- The preflight request is implemented in [vault_kvhelpers.go:15](https://github.com/concourse/concourse/blob/d0130396c1cb50c6d114bd55317ffa2d121d7b29/atc/creds/vault/vault_kvhelpers.go#L15) and sends GET to /v1/sys/internal/ui/mounts/<path>.
- After preflight, the actual secret read occurs in [api_client.go:79](https://github.com/concourse/concourse/blob/d0130396c1cb50c6d114bd55317ffa2d121d7b29/atc/creds/vault/api_client.go#L79).
- this was introduced with following PR: #6115

### Impact

Because the KV engine version is a static property of the mount, performing this preflight request on every read is redundant. At scale, this effectively doubles the number of Vault API calls, increasing latency and putting unnecessary pressure on Vault.

### Steps to Reproduce

1. Start Concourse configured with Vault credential manager.
2. Ensure a pipeline/task references one or more Vault-backed vars.
3. Enable Vault audit logs. Or build Concourse version with logs.
4. Trigger a build that resolves secrets.
5. Observe that each secret resolution produces:
    - one preflight call to /v1/sys/internal/ui/mounts/<secret-path>
    - one data read call to the secret endpoint.

### Expected Results

KV engine version should be determined once per mount and reused for subsequent reads under the same mount.

### Actual Results

KV version is revalidated for each secret read, resulting in two calls per secret.

### Web Node(s) configuration

I've used [vault.yml](https://github.com/concourse/concourse/blob/master/hack/overrides/vault.yml) to setup local environment

### Worker(s) configuration

_No response_

### Concourse Version

8.1.1(but it is not applicable)

### Browser (if applicable)

_No response_

### Did this use to work?

No

### PR DESCRIPTION
**Pull request by IvanChalukov**
## Changes proposed by this PR

closes #9514

This PR adds KV mount version caching for Vault so Concourse does not run mount preflight on every secret read.

#### What changed
- Cache KV mount version by mount path.
- Reuse cached value on subsequent reads under the same mount.
- Keep preflight behavior for cache misses.

#### Enablement

- Feature flag env var: CONCOURSE_VAULT_ENABLE_KV_MOUNT_CACHE. Values are "true" or "false". Default behavior in this change: cache is disabled unless explicitly set (set to "true" to enable)
- For `var_sources`:
```yml
var_sources:
  - name: main
    type: vault
    config:
      url: https://vault:8200
      path_prefix: /concourse
      namespace: main
      lookup_templates:
        - /main/test-iamge/{{.Secret}}
      auth_backend: token
      client_token: ...
      insecure_skip_verify: true
      enable_kv_mount_cache: true
```

### CODE REVIEW

**Review by Kump3r — APPROVED** [review]
Looks good to me, I tested by configuring the compose yaml with an internal Vault we use trough approle auth. I used debug logs as I do not have server side access to the Vault and the web container doesn't have `ngrep`, `wireshark` etc. and the cache is in memory. As I already spoke to you what is TBD from my perspective is the docs, helm and bosh packaging stuff. Logs from testing in collapsed details section.
<details>

Logs enabled:

```
docker logs fork-concourse-ivan-web-1 | grep kv-mount-cache
{"timestamp":"2026-04-20T08:30:12.879820721Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-miss","data":{"name":"vault","secret-path":"test/test/concourse/test-vault/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T08:30:13.005661930Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-fetched-from-vault","data":{"is-v2":true,"mount-path":"test/","name":"vault","secret-path":"test/test/concourse/test-vault/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T08:30:13.005750680Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-stored","data":{"is-v2":true,"mount-path":"test/","name":"vault","session":"7"}}
{"timestamp":"2026-04-20T08:30:13.057563763Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-hit","data":{"is-v2":true,"mount-path":"test/","name":"vault","secret-path":"test/test/concourse/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T08:32:22.410623961Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-hit","data":{"is-v2":true,"mount-path":"test/","name":"vault","secret-path":"test/test/concourse/test-vault/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T08:32:22.694515545Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-hit","data":{"is-v2":true,"mount-path":"test/","name":"vault","secret-path":"test/test/concourse/test-secret/","session":"7"}}
```

Logs disabled:

```
docker logs fork-concourse-ivan-web-1 | grep kv-mount-cache
{"timestamp":"2026-04-20T09:36:32.028043715Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-disabled","data":{"name":"vault","secret-path":"test/test/concourse/test-vault/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T09:36:32.324927382Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-disabled","data":{"name":"vault","secret-path":"test/test/concourse/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T09:38:11.160152428Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-disabled","data":{"name":"vault","secret-path":"test/test/concourse/test-vault/test-secret/","session":"7"}}
{"timestamp":"2026-04-20T09:38:11.547221345Z","level":"debug","source":"atc","message":"atc.credential-manager.kv-mount-cache-disabled","data":{"name":"vault","secret-path":"test/test/concourse/test-secret/","session":"7"}}
```
</details>

Edit: let me know if you need help/reviews in the packaging stuff as well.

File: atc/creds/vault/vault_test.go
Comment (taylorsilva) [inline atc/creds/vault/vault_test.go:1]: For these tests, why is the cache disabled for the v2 client and enabled for the v1 client?

File: integration/creds/vault_test.go [hunk 1]
```diff
@@ -108,12 +108,78 @@ func TestVaultV2WithUnmountPath(t *testing.T) {
...
 func setupVaultAuth(t *testing.T, vault vaulttest.Cmd) {
 	// set up a policy for Concourse
 	vault.WithInput(bytes.NewBufferString(`
 		path "concourse/*" {
 			policy = "read"
 		}
+		path "secret*" {
+			policy = "read"
+		}
 	`)).Run(t, "policy", "write", "concourse", "-")
```
Comment (taylorsilva) [inline integration/creds/vault_test.go:117]: nit: is this needed? A `/secret` mount doesn't appear to be used in the tests here.

File: integration/creds/vault_test.go
Comment (taylorsilva) [inline integration/creds/vault_test.go:1]: I'm not sure integration tests are very useful here. I think these tests pass regardless if the KV cache is enabled or not.

Update: yup, they pass even when the cache is disabled.

Integration tests take longer, so I'm always a bit hesitant to add them. As-is, these tests don't error if the mount cache is not being used.

**Comment by taylorsilva** [comment]
I've gone ahead and removed the integration-level tests and added unit tests instead that fail if the cache is not hit on subsequent calls.

Cleaned up the small nits I mentioned as well.

I didn't make any other changes. Everything else LGTM. Feature works as expected. TY for working on this Ivan!

File: integration/creds/vault_test.go (hunk 1 above)
Comment (IvanChalukov) [reply integration/creds/vault_test.go:117]: It is a leftover from testing, it should be deleted as you did. Thanks for that!

File: integration/creds/vault_test.go
Comment (IvanChalukov) [reply integration/creds/vault_test.go:1]: Thanks for raising your concerns about the integration tests. I was unsure where the functionality should be validated and didn’t realize the tests would pass in both scenarios (enabled and disabled).

I’ll keep this in mind for future PRs.

**Comment by IvanChalukov** [comment]
@taylorsilva I've opened PRs for packaging stuff:
- bosh deployment introduction of env variable - https://github.com/concourse/concourse-bosh-release/pull/195
- helm chart introduction of env variable - https://github.com/concourse/concourse-chart/pull/414
- documentation in `The Vault credential manager` and `var_sources` config - https://github.com/concourse/docs/pull/600

**Comment by taylorsilva** [comment]
You da bestttt 🙏 👏
