### PR TITLE
ensure failed containers are cleaned from the workers

### LINKED ISSUE #4562: Worker and DB container state can fall out of sync when Garden is slow to respond
Looking at the containers listed in the worker. Many are not in the db.
```
worker/4fd44d6a-2376-4ec8-a187-25b25087e2a5:/var/vcap/data/worker/work/depot# ls -lt
total 692
drwxr-xr-x 2 root root 4096 Oct  4 18:45 db0ad945-cd43-4924-5359-aba00c3b38bd
drwxr-xr-x 3 root root 4096 Oct  4 18:45 15980398-ff0c-4ca8-50c4-c7cbf6d982b9
drwxr-xr-x 3 root root 4096 Oct  4 18:45 3c9ecd39-45b6-43ed-7bb4-bdf869a0ba31
drwxr-xr-x 3 root root 4096 Oct  4 18:45 826d3627-3d3c-4ee9-5844-abaf2255c9ad
drwxr-xr-x 3 root root 4096 Oct  4 18:45 6c12c532-9570-4fcd-707a-b3fa9f9e8b84
drwxr-xr-x 3 root root 4096 Oct  4 18:45 47bf16c7-4951-4f6b-5322-e23e455239bb
drwxr-xr-x 3 root root 4096 Oct  4 18:45 6c1b8539-e2ac-41fb-4522-98cd7a4a8c4b
drwxr-xr-x 3 root root 4096 Oct  4 18:45 068c55b0-68eb-428d-76ec-feb25420e044
drwxr-xr-x 3 root root 4096 Oct  4 18:45 59ab81b5-debe-4a7d-4c8f-5674cc26e826
drwxr-xr-x 3 root root 4096 Oct  4 18:45 9304b72b-0f37-4ee4-53b4-244276691f4d
drwxr-xr-x 3 root root 4096 Oct  4 18:45 65812853-3116-4f80-4f35-bcd3fdeeb989
drwxr-xr-x 3 root root 4096 Oct  4 18:45 2311313d-bb62-4188-4e68-5a0a4aa598a6
drwxr-xr-x 3 root root 4096 Oct  4 18:45 661fa51c-e91d-43df-656b-2968aea4ed0e
drwxr-xr-x 3 root root 4096 Oct  4 18:45 a58f5d52-c75d-477c-5751-9ce5fea39a89
drwxr-xr-x 3 root root 4096 Oct  4 18:45 d2bc537a-2de3-433e-744c-dff35c64e907
drwxr-xr-x 3 root root 4096 Oct  4 18:45 1d926844-a522-41eb-7d32-81778cd0167d
drwxr-xr-x 3 root root 4096 Oct  4 18:45 7c857a43-66fd-475f-5fff-9c8ea7a7557e
drwxr-xr-x 3 root root 4096 Oct  4 18:45 d77fe063-63f9-4baf-46f8-8c8946d392e8
drwxr-xr-x 3 root root 4096 Oct  4 18:44 6ede9d02-bf79-48c5-7da4-fb081b00effd
drwxr-xr-x 3 root root 4096 Oct  4 18:44 e447972b-221e-4ee0-4cab-0716fa47d876
drwxr-xr-x 3 root root 4096 Oct  4 18:44 7ba71dd6-3d45-4ade-6bfe-e8edf9b56b33
drwxr-xr-x 3 root root 4096 Oct  4 18:44 390b48cc-50ed-4926-5520-2998f0288121
drwxr-xr-x 3 root root 4096 Oct  4 18:44 c794cedb-6b83-4573-4738-521da612cee3
drwxr-xr-x 3 root root 4096 Oct  4 18:44 5e8e5252-922f-4106-525a-ca56b0e45947
drwxr-xr-x 3 root root 4096 Oct  4 18:44 735cedc6-7ac5-4367-68b7-44ce832cae5a
drwxr-xr-x 3 root root 4096 Oct  4 18:44 63490a87-442a-465b-4a57-33fc6e6a9428
drwxr-xr-x 3 root root 4096 Oct  4 18:44 5950a806-3045-4df5-5115-bda1011e613b
drwxr-xr-x 3 root root 4096 Oct  4 18:44 6f0a0dde-0105-4898-7738-2d1e69d158d1
drwxr-xr-x 3 root root 4096 Oct  4 18:44 dc718e4e-ae30-494a-7476-38bb965b6f16
drwxr-xr-x 3 root root 4096 Oct  4 18:44 44ec555a-905a-4256-57cf-01a6ad0146ad
drwxr-xr-x 3 root root 4096 Oct  4 18:44 898777fb-97af-41e8-72ee-f9ef3f1c9f15
drwxr-xr-x 3 root root 4096 Oct  4 18:44 3ce1ea53-7f67-4afe-7b8e-b37c4e064749
drwxr-xr-x 3 root root 4096 Oct  4 18:44 865730ea-18af-4c12-74fc-6cf377c5e247
drwxr-xr-x 3 root root 4096 Oct  4 18:44 63f3e613-923d-4d0d-58c3-27d3379717cd
drwxr-xr-x 3 root root 4096 Oct  4 18:44 1c363bec-1c7f-404c-7d92-092eb74b8e98
drwxr-xr-x 3 root root 4096 Oct  4 18:44 f8c8bdbb-6d25-4aa3-6f5b-e6769b8dd1aa
drwxr-xr-x 3 root root 4096 Oct  4 18:44 b5377ece-9718-4d36-44a8-f38f5841da41
drwxr-xr-x 3 root root 4096 Oct  4 18:44 483b3f27-c1e3-4448-6808-4432c1822365
drwxr-xr-x 3 root root 4096 Oct  4 18:44 a3de2334-5f9e-45d3-5840-28631b4a50eb
drwxr-xr-x 3 root root 4096 Oct  4 18:44 67636b81-a045-4aca-5645-1a0b27ab699d
drwxr-xr-x 3 root root 4096 Oct  4 18:44 a2b73e3b-f4d5-48ae-45d7-f82cce4548c0
drwxr-xr-x 3 root root 4096 Oct  4 18:44 d0f880f3-ced6-49d8-6e86-cacd0c6f2be9
drwxr-xr-x 3 root root 4096 Oct  4 18:44 ff216c44-9718-4d0f-4015-e100e5cad00d
drwxr-xr-x 3 root root 4096 Oct  4 18:44 f35671ff-7c97-4677-440a-1e116765fc7e
drwxr-xr-x 3 root root 4096 Oct  4 18:44 e4059d92-57fa-4412-6e65-577f65a0137b
drwxr-xr-x 3 root root 4096 Oct  4 18:44 48e7c243-385e-4855-541f-2ce4987b9070
drwxr-xr-x 3 root root 4096 Oct  4 18:44 5e4fc484-615b-4df3-4f84-1eb68de8bd45
drwxr-xr-x 3 root root 4096 Oct  4 18:44 b11ef2b7-f781-451d-57e1-350c796d26a7
drwxr-xr-x 3 root root 4096 Oct  4 18:44 e4fa971d-f817-4744-7462-9ae76eb8aa45
drwxr-xr-x 3 root root 4096 Oct  4 18:44 4347c636-dc68-4c84-517d-3e4f16d796c4
drwxr-xr-x 3 root root 4096 Oct  4 18:36 27572083-b022-4bf2-5042-004a3314f4b5
drwxr-xr-x 2 root root 4096 Oct  4 18:33 e4f73679-d54d-4eb1-7192-492843096083
drwxr-xr-x 2 root root 4096 Oct  4 18:32 121d6a72-d5b5-4b63-4884-3d826dcb4b28
drwxr-xr-x 2 root root 4096 Oct  4 18:30 a7442694-e11e-4e56-7f0c-88d4b7e472d6
drwxr-xr-x 3 root root 4096 Oct  4 18:29 c855960a-5ee3-440b-6531-88af0fcac897
drwxr-xr-x 2 root root 4096 Oct  4 18:12 56d091ee-201a-40f7-4375-9c6668136b9c
drwxr-xr-x 3 root root 4096 Oct  4 18:06 bba0bb9a-f88e-4b0e-7029-9bb98b5363d8
drwxr-xr-x 3 root root 4096 Oct  4 14:50 03e0805c-a24d-4cdd-4f8f-46587d19d43e
drwxr-xr-x 3 root root 4096 Oct  4 14:48 3b337afe-836b-4ac7-41a9-a6350db47830
drwxr-xr-x 2 root root 4096 Oct  4 14:00 7c33543b-c75d-4ed6-61e1-74758447fbdd
drwxr-xr-x 2 root root 4096 Oct  4 13:29 385cb252-128e-4ed8-4315-59c4c3321804
drwxr-xr-x 2 root root 4096 Oct  4 13:29 4f479be9-fb94-4e21-76d2-54e32ea7896c
drwxr-xr-x 3 root root 4096 Oct  4 13:00 e9f3fc9d-0825-4463-5819-86bed1994073
drwxr-xr-x 3 root root 4096 Oct  4 13:00 7dbe1e6e-6560-4c99-56fb-a0f42d867052
drwxr-xr-x 3 root root 4096 Oct  4 13:00 6eda50cb-3dcf-4b83-4e5a-23a8a5b26f14
drwxr-xr-x 3 root root 4096 Oct  4 13:00 3c8300a4-0673-42f4-45e9-9dd96bb43b53
drwxr-xr-x 3 root root 4096 Oct  4 13:00 0424089b-f4ef-4f58-4d09-1661a55e19da
drwxr-xr-x 3 root root 4096 Oct  4 13:00 4a6cf592-3d54-43c3-6ed8-9dd2f91bb1d7
drwxr-xr-x 3 root root 4096 Oct  4 13:00 07d91157-912c-4afb-59db-41cf162279d9

---------EVERYTHING BELOW NOT IN DB------------------------------------------
drwxr-xr-x 3 root root 4096 Oct  4 11:19 ab36ef51-6144-4637-6ef8-be93299aad32
drwxr-xr-x 2 root root 4096 Oct  4 06:08 427a8176-0d3c-449e-4fc6-ba2f8afb6566
drwxr-xr-x 2 root root 4096 Oct  4 06:01 81b9a438-4cb9-42a4-79a7-956feb64a4b0
drwxr-xr-x 2 root root 4096 Oct  4 05:47 06421add-ca31-4991-6363-cf5b73f9367d
drwxr-xr-x 2 root root 4096 Oct  4 05:47 ef831ace-280c-445c-6c3d-1830ee1ae787
drwxr-xr-x 2 root root 4096 Oct  4 05:47 e57faad4-6c09-4411-67a5-7ece20583718
drwxr-xr-x 2 root root 4096 Oct  4 05:40 6ddddbb6-33ae-483d-665f-0ca387385f5e
drwxr-xr-x 2 root root 4096 Oct  4 05:40 0dbe75d9-6432-45eb-63a5-4b3880ea6fa2
drwxr-xr-x 2 root root 4096 Oct  4 05:39 ab22e748-abc9-4e2d-64a2-049feb1d89e4
drwxr-xr-x 2 root root 4096 Oct  4 05:39 a37f46cb-bc73-45ab-7b07-d49d19c28ab2
drwxr-xr-x 2 root root 4096 Oct  4 05:39 3636ec3c-5df4-452a-76cb-ac0b92ef2007
drwxr-xr-x 2 root root 4096 Oct  4 05:39 2f2f6bcd-ce12-49f3-7ac8-660058a7eac8
drwxr-xr-x 2 root root 4096 Oct  4 05:39 77fa9ee2-f790-4ae5-4c4b-6c916b70c2d5
drwxr-xr-x 2 root root 4096 Oct  4 05:39 aad86967-f152-4e4e-6ba7-7f375a242969
drwxr-xr-x 2 root root 4096 Oct  4 05:39 175841d4-928f-4266-45b9-c132f16b4eff
drwxr-xr-x 2 root root 4096 Oct  4 05:39 edee5128-79de-4374-60f8-b260c2fd9d09
drwxr-xr-x 2 root root 4096 Oct  4 05:39 77bbbf96-9073-4f4b-74ce-0ab02d9d76f5
drwxr-xr-x 3 root root 4096 Oct  4 05:39 2dd8a1fb-5382-4c2c-4b2f-cdbec4668a2f
drwxr-xr-x 3 root root 4096 Oct  4 05:36 4c031f2a-19fb-4396-6404-72186c781315
drwxr-xr-x 2 root root 4096 Oct  4 05:20 33081958-476d-4d60-52e8-6df1382c24f9
drwxr-xr-x 2 root root 4096 Oct  4 05:20 3dbca2ba-a403-4d83-74e0-d138fc048f18
drwxr-xr-x 2 root root 4096 Oct  4 05:20 e3248d79-6825-45c2-6ce1-1d21b2de384a
drwxr-xr-x 2 root root 4096 Oct  4 05:20 67ecb3e0-43a3-448a-4a0a-dd66c6d0cae0
drwxr-xr-x 2 root root 4096 Oct  3 21:46 9b9678ca-3eab-43ae-49e8-195c1cb6d74e
drwxr-xr-x 2 root root 4096 Oct  3 21:35 16043c0c-c60a-4a09-7d9d-62581b0b97af
drwxr-xr-x 2 root root 4096 Oct  3 21:35 aa8aa23f-6764-432d-500c-852705ce0140
drwxr-xr-x 2 root root 4096 Oct  3 21:33 f1851ed7-01aa-4c3d-7f23-518e9bba29d6
drwxr-xr-x 2 root root 4096 Oct  3 21:33 a512d091-e381-4323-6a29-ee04feae0944
drwxr-xr-x 2 root root 4096 Oct  3 21:33 8f57cce3-e6e7-4db9-4339-1d7a867ae58e
drwxr-xr-x 2 root root 4096 Oct  3 21:33 95c030cf-b8da-4156-6969-223d3e76115c
drwxr-xr-x 2 root root 4096 Oct  3 21:33 3b82899c-1ec4-45ae-47b2-a59f485c555b
drwxr-xr-x 2 root root 4096 Oct  3 21:33 a8032a34-dcc2-44df-4c74-b01e47617a54
drwxr-xr-x 2 root root 4096 Oct  3 21:33 2480e77d-9642-473d-6594-1f7cc8752689
drwxr-xr-x 2 root root 4096 Oct  3 21:33 f3a0e722-6a6c-411d-6737-a79c6b80e374
drwxr-xr-x 2 root root 4096 Oct  3 21:33 22d19fdc-cc8c-45b9-4c1b-b1a72298af65
drwxr-xr-x 2 root root 4096 Oct  3 21:33 704568f0-5827-4ea6-5a52-4a2ebfd2fd48
drwxr-xr-x 2 root root 4096 Oct  3 21:33 340d4230-e184-4eeb-7774-5b65e2bb8dd0
drwxr-xr-x 2 root root 4096 Oct  3 21:33 813bf374-ba91-4c06-62f1-f0b71b52d46e
drwxr-xr-x 2 root root 4096 Oct  3 21:33 d058bde4-c022-4e54-43ef-9eea2d49c1ee
drwxr-xr-x 2 root root 4096 Oct  3 21:33 43318cff-aa10-496e-6e6f-4c2f63fad20d
drwxr-xr-x 2 root root 4096 Oct  3 21:33 1d1a44a7-22e3-4444-655a-47dee551ed71
drwxr-xr-x 2 root root 4096 Oct  3 21:33 eb1e33f4-38e0-468f-4d4c-270a2d550f48
drwxr-xr-x 2 root root 4096 Oct  3 21:33 2e16063a-16b1-4d62-5560-3af1a71dcb7f
drwxr-xr-x 2 root root 4096 Oct  3 21:33 90121faa-ce5a-46fc-5eeb-d6a22ab50a49
drwxr-xr-x 2 root root 4096 Oct  3 21:33 65c5b05d-cbd0-457e-6ca5-1ec95e5bce95
drwxr-xr-x 2 root root 4096 Oct  3 21:33 c37bf0ad-bc73-4dcb-485b-7589636533b1
drwxr-xr-x 2 root root 4096 Oct  3 21:33 eccbf13f-0689-407e-4c4a-231a8ad968dc
drwxr-xr-x 2 root root 4096 Oct  3 21:33 21efd4fa-aca9-4290-50e2-a41a6f67d121
drwxr-xr-x 2 root root 4096 Oct  3 21:33 e7acbfa3-ccac-4cf0-58e1-41c0a82ae5e7
drwxr-xr-x 2 root root 4096 Oct  3 21:27 5fcb3cdc-27cb-4de6-5128-e91b1515ec1e
drwxr-xr-x 2 root root 4096 Oct  3 21:27 59a2ce9e-5b99-436d-77c1-4446352485a1
drwxr-xr-x 2 root root 4096 Oct  3 21:27 ffaecdb5-6d6e-44d3-442d-087b369dd9f4
drwxr-xr-x 2 root root 4096 Oct  3 21:27 9b996f88-fabd-451c-708c-3af006b5f5be
drwxr-xr-x 2 root root 4096 Oct  3 21:27 f201fc8a-8686-4da6-7a8b-358809e0ed25
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a009b4a7-00c6-4546-4174-6b1b6c77cfe0
drwxr-xr-x 2 root root 4096 Oct  3 21:27 02af8155-c7af-4e70-434e-14acbd841609
drwxr-xr-x 2 root root 4096 Oct  3 21:27 d1d63ba7-3a65-453b-71f0-12b4ebc37cf4
drwxr-xr-x 2 root root 4096 Oct  3 21:27 200d977b-9c68-4687-4ce7-6d7dfddd8bc8
drwxr-xr-x 2 root root 4096 Oct  3 21:27 23e56452-bbc8-4196-5b88-b5aaea898541
drwxr-xr-x 2 root root 4096 Oct  3 21:27 372a93de-3b4d-479e-44dd-a234dcde45a1
drwxr-xr-x 2 root root 4096 Oct  3 21:27 f1664a84-7201-44af-4b9c-b83369677e98
drwxr-xr-x 2 root root 4096 Oct  3 21:27 07f1dae2-2cc0-4594-454c-c3922d287d42
drwxr-xr-x 2 root root 4096 Oct  3 21:27 64ad861c-e1fa-4991-625c-8192781b8d49
drwxr-xr-x 2 root root 4096 Oct  3 21:27 e790bfcc-633e-435b-6908-4851f6d45504
drwxr-xr-x 2 root root 4096 Oct  3 21:27 154f7e59-c32e-4f5f-43c1-eeedd34a793f
drwxr-xr-x 2 root root 4096 Oct  3 21:27 2f29d147-7567-4f62-7b2a-c9681a51f6af
drwxr-xr-x 2 root root 4096 Oct  3 21:27 5682d79c-f4c3-4a68-6231-b5de9b625550
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a3f506e5-a601-49c9-7cdc-361b2bbe7a07
drwxr-xr-x 2 root root 4096 Oct  3 21:27 84f4dd13-a40d-44e8-7c4a-f57633fa4027
drwxr-xr-x 2 root root 4096 Oct  3 21:27 b83f3b7c-3cb8-4634-5ee2-d2f1378506b4
drwxr-xr-x 2 root root 4096 Oct  3 21:27 c3d7453a-0a69-40e0-78c2-d317a2d888f0
drwxr-xr-x 2 root root 4096 Oct  3 21:27 6ce53524-5391-4234-52a4-76d29256b9bd
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a4f0e7a9-eeff-4ee9-460f-2b27538e5b49
drwxr-xr-x 2 root root 4096 Oct  3 21:27 4c81861a-fb0f-48ed-6c01-885fd6c88b92
drwxr-xr-x 2 root root 4096 Oct  3 21:27 1dcd0a1d-8daa-44ef-61cc-39a4358fe110
drwxr-xr-x 2 root root 4096 Oct  3 21:27 c160aefa-fd2f-484d-7cc9-9b4d09bf050b
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a5e14932-74ac-40be-60cc-fbf2f2fbc99b
drwxr-xr-x 2 root root 4096 Oct  3 21:27 7fc10595-45ae-4759-5880-caa679f2f309
drwxr-xr-x 2 root root 4096 Oct  3 21:27 7619ca2c-b3f4-4b3f-67ab-82ba42ec237f
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a8cb6250-ab97-4992-790c-1bf5a22b7553
drwxr-xr-x 2 root root 4096 Oct  3 21:27 00f28f6a-e826-4e5c-4f00-ff2953c4b332
drwxr-xr-x 2 root root 4096 Oct  3 21:27 2a7ad7ec-16d6-4395-6381-b7721c7fa132
drwxr-xr-x 2 root root 4096 Oct  3 21:27 d4b13cb4-353c-44af-6c64-ae94751e9d78
drwxr-xr-x 2 root root 4096 Oct  3 21:27 6f84072a-0342-41c1-537d-361490cb2b82
drwxr-xr-x 2 root root 4096 Oct  3 21:27 13a9b3f8-48cc-4ce6-4b59-2c9e9e7cd873
drwxr-xr-x 2 root root 4096 Oct  3 21:27 ef43f863-1257-4b4d-4eda-c036c2e03845
drwxr-xr-x 2 root root 4096 Oct  3 21:27 4baad6ad-2d66-4bc7-42b3-b27527d4d2d4
drwxr-xr-x 2 root root 4096 Oct  3 21:27 ae251242-068f-4f58-5d62-0e7cbf5673d5
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a9d463c2-5a62-4433-5c6a-beda1ffd1e57
drwxr-xr-x 2 root root 4096 Oct  3 21:27 a230877b-f43b-4b7f-7a4f-217b0e5eef40
drwxr-xr-x 2 root root 4096 Oct  3 21:27 72621ea7-7a27-4e37-4c2e-f18360f0c505
drwxr-xr-x 2 root root 4096 Oct  3 21:26 2714a34a-9f21-4566-5092-56276a5ad53c
drwxr-xr-x 2 root root 4096 Oct  3 21:23 cd7c49fa-00c5-4dd8-468e-e339adb494af
drwxr-xr-x 2 root root 4096 Oct  3 21:22 9493cebb-a6e1-4bd0-44ef-5668e5c5e737
drwxr-xr-x 2 root root 4096 Oct  3 21:22 ce4e2890-f67e-481c-4dbd-e9648f51b20e
drwxr-xr-x 2 root root 4096 Oct  3 21:22 a6ea97d8-ce99-4272-68d2-141aec9baa1c
drwxr-xr-x 2 root root 4096 Oct  3 21:22 8a918e79-0e8b-4d5e-60d7-c3487a196278
drwxr-xr-x 2 root root 4096 Oct  3 21:22 80d84b7d-c1ef-461b-6770-eeca3380dd3d
drwxr-xr-x 2 root root 4096 Oct  3 21:22 1366ffba-67ed-4392-5c16-52ce37fdb43f
drwxr-xr-x 3 root root 4096 Oct  3 16:25 72b9b6fb-113a-4842-5cc6-26c3e17a886f
drwxr-xr-x 3 root root 4096 Oct  3 16:24 d6b64f67-c77b-4fbc-53c8-92246c85f488
drwxr-xr-x 3 root root 4096 Oct  3 16:24 2290150a-a1f8-4ecf-49d1-ddc239151a25
drwxr-xr-x 3 root root 4096 Oct  2 17:35 e1bd5dd3-d4bd-4b36-7217-c46e9499a2ab
drwxr-xr-x 3 root root 4096 Oct  2 17:35 a6f3ec74-4aa7-487c-7e77-9e603394cb74
```

Looks like this was a 5.5 change when we introduced 5 min timeout to the garden client
https://github.com/concourse/concourse/blob/master/atc/worker/gclient/factory.go#L54
Some Context: We added in this timeout to fix cases where users would see checks hang indefinitely. 

its possible that garden received the request successfully but is taking a really long time to service
the request. Longer than the 5 min timeout we provide. In this situation we took around 7 mins. Garden does not clean up the canceled requests containers so it continues to exist on the machine.

~We might be seeing a spike because the retrier then kicks in and tries to make another container.~ (This is probably not happening because, we decide what handle to give the container and the same handle would cause the request to fail in garden)

Every handle in the depot dir not present in the db had the following output.
```
Oct 03 17:33:07 4fd44d6a-2376-4ec8-a187-25b25087e2a5.worker.private.concourse-prod.bosh worker/rs2 {"timestamp":"2019-10-03T21:33:07.457158790Z","level":"info","source":"guardian","message":"guardian.create.start","data":{"handle":"8f57cce3-e6e7-4db9-4339-1d7a867ae58e","session":"598"}}
Oct 03 17:38:07 6ae730cc-cbab-4de6-80ff-ebf529fc3f44.web.web.concourse-prod.bosh web/rs2 {"timestamp":"2019-10-03T21:38:07.458377679Z","level":"error","source":"atc","message":"atc.lidar-checker.check-step.failed-to-create-container-in-garden","data":{"check":13955958,"container":"8f57cce3-e6e7-4db9-4339-1d7a867ae58e","error":"Post http://127.0.0.1:8080/containers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)","session":"25.2","step-name":"resource-pr"}}
Oct 03 17:40:59 4fd44d6a-2376-4ec8-a187-25b25087e2a5.worker.private.concourse-prod.bosh worker/rs2 {"timestamp":"2019-10-03T21:40:58.897175427Z","level":"info","source":"guardian","message":"guardian.create.created","data":{"handle":"8f57cce3-e6e7-4db9-4339-1d7a867ae58e","session":"598"}}
Oct 03 17:40:59 4fd44d6a-2376-4ec8-a187-25b25087e2a5.worker.private.concourse-prod.bosh worker/rs2 {"timestamp":"2019-10-03T21:40:58.897265347Z","level":"info","source":"guardian","message":"guardian.api.garden-server.create.created","data":{"request":{"Handle":"8f57cce3-e6e7-4db9-4339-1d7a867ae58e","GraceTime":0,"RootFSPath":"raw:///var/vcap/data/worker/work/volumes/live/3ca45493-a667-4722-7e09-11206565aeaf/volume/rootfs","BindMounts":[{"src_path":"/var/vcap/data/worker/work/volumes/live/368f204d-1535-44ca-4c25-a53def4f6082/volume","dst_path":"/etc/ssl/certs"},{"src_path":"/var/vcap/data/worker/work/volumes/live/3d733fcc-2829-4a34-62cf-737c6a302a11/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.715"}}
```

There is no definitive proof that we won't find/introduce more edge cases such as these. It would be worth while to build a catch all gc to delete un-synced state on the worker side.
And report metrics when this happens so it still surfaces problems and allows us to investigate without the cluster going into a failure state.

### PR DESCRIPTION
**Pull request by kcmannem**
Signed-off-by: Krishna Mannem <kmannem@pivotal.io>
Co-authored-by: Divya Dadlani <ddadlani@pivotal.io>

# Existing Issue
Fixes #4562 

# Changes proposed in this pull request
* when gc-ing failed containers, mark them as destroying rather than simply deleting the row
* this will ensure that if they failed due to a timeout on the gardenClient.Create call, the resulting garden container will be picked up by the sweeper.
* This should not cause any errors when deleting containers in Garden because the list of destroying containers depends upon the list of containers that the worker reports

# Contributor Checklist
- [X] Unit tests
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed

### CODE REVIEW

File: atc/db/container.go [hunk 1]
```diff
@@ -385,26 +385,44 @@ func (container *failedContainer) Handle() string              { return containe
...
+		Set("state", atc.ContainerStateDestroying).
+		Where(sq.And{
+			sq.Eq{"id": container.id},
+			sq.Or{
+				sq.Eq{"state": string(atc.ContainerStateDestroying)},
+				sq.Eq{"state": string(atc.ContainerStateFailed)},
+				sq.Eq{"state": string(atc.ContainerStateCreated)},
+			},
 		}).
+		PlaceholderFormat(sq.Dollar).
```
Comment (clarafu) [inline atc/db/container.go]: I don't think we need this line because the `psql` object you are using already has the placeholder format set. (https://github.com/concourse/concourse/blob/master/atc/db/psql.go#L8)

File: atc/db/container.go [hunk 2]
```diff
@@ -385,26 +385,44 @@ func (container *failedContainer) Handle() string              { return containe
...
-		Where(sq.Eq{
-			"id":    container.id,
-			"state": atc.ContainerStateFailed,
+func (container *failedContainer) Destroy() (DestroyingContainer, error) {
+	result, err := psql.Update("containers").
+		Set("state", atc.ContainerStateDestroying).
+		Where(sq.And{
+			sq.Eq{"id": container.id},
+			sq.Or{
+				sq.Eq{"state": string(atc.ContainerStateDestroying)},
```
Comment (clarafu) [inline atc/db/container.go]: I might just be missing some context but I'm just curious, why are allowing destroying and created containers to be updated within a failed container object?

File: atc/db/container.go [hunk 3]
```diff
@@ -385,26 +385,44 @@ func (container *failedContainer) Handle() string              { return containe
...
+				sq.Eq{"state": string(atc.ContainerStateFailed)},
+				sq.Eq{"state": string(atc.ContainerStateCreated)},
+			},
 		}).
+		PlaceholderFormat(sq.Dollar).
 		RunWith(container.conn).
 		Exec()
 	if err != nil {
-		return false, err
+		if err == sql.ErrNoRows {
```
Comment (clarafu) [inline atc/db/container.go]: I'm not sure if `Exec()` ever returns `ErrNoRows`? Might want to double check though but I'm _pretty_ sure it doesn't?? But please correct me if I'm wrong.

File: atc/db/container_repository.go [hunk 4]
```diff
@@ -346,19 +346,32 @@ func scanContainer(row sq.RowScanner, conn Conn) (CreatingContainer, CreatedCont
...
 	}
 
-	return int(failedContainersLen), nil
+	for _, failedContainer := range failedContainers {
+		_, err = failedContainer.Destroy()
+		if err != nil {
+			return 0, err
+		}
+	}
+	return numFailedContainers, nil
```
Comment (clarafu) [inline atc/db/container_repository.go]: nit: Might just be preference but I think you don't need a var for `numFailedContainers` since you can use `len(failedContainers)`?

File: atc/db/container_repository.go [hunk 5]
```diff
@@ -346,19 +346,32 @@ func scanContainer(row sq.RowScanner, conn Conn) (CreatingContainer, CreatedCont
 }
 
 func (repository *containerRepository) DestroyFailedContainers() (int, error) {
-	result, err := sq.Delete("containers").
+	rows, err := selectContainers().
```
Comment (clarafu) [inline atc/db/container_repository.go]: Might just be something to think about but I'm a little unsure about the fact that we select out all these failed containers and then update the state one by one without using the return value of the `Destroy()` method. It seems like in hindsight it would be easiest and most efficient to just have this `DestroyFailedContainers` method to just straight up update all the failed containers to `destroying` state? Maybe there a reason why we need to do it this way that I'm missing?

File: atc/db/container.go (hunk 2 above)
Comment (kcmannem) [reply atc/db/container.go]: copy pasta

File: atc/db/container_repository.go (hunk 5 above)
Comment (kcmannem) [reply atc/db/container_repository.go]: we saw that all the state transitions were happening through db/container function calls. Its a good point that we can bypass everything; we were just trying to be clean but I guess no one will actually call failedContainer.Destroy() other than container_repo

**Comment by kcmannem** [comment]
@clarafu thanks for checking this! made the changes you suggested.

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-jwinters this needs a v5.7.0 release note
