### PR TITLE
Better abort tracking

### LINKED ISSUE #1585: Aborting a started build prior to an ATC tracking it will result in an orphaned, uncompleted build, still running
# Bug Report

I think [this block of code](https://github.com/concourse/atc/blob/e0434a2d057a261b17d654dbd8b110ba3b60a97c/engine/db_engine.go#L162-L170) does basically nothing, and hasn't since its inception.

In the case where a build is tracked and then the ATC is restarted, it's possible that a build is aborted prior to any ATC re-tracking it. This is easier to reproduce with two ATCs by doing the following:

* Start the build, make note of the ATC that's tracking it.
* Wait for the other ATC's tracking to fire (this is on a 10 second interval).
* Stop the ATC that's tracking it.
* Abort the build via the remaining ATC.

Right now, the `engineBuild.Abort` line will just write a signal to a channel that no one's reading from. To have gotten that far in the method, no one will have been tracking the build (the first thing it does is acquire a lock). In addition, no one will *ever* track the build by then, since after it acquires the lock it sets the status to `aborted`, excluding it from build tracking (which only looks at `started`).

This will result in a build's containers never actually being interrupted, and a build that is in status `aborted` but never marked `completed` in the database. This will result in the build's containers leaking, even, as we only mark `completed` builds non-interceptible.

### PR DESCRIPTION
**Pull request by pivotal-jwinters**
This adds an aborted column to track aborted builds instead of immediately updating the build status to `aborted`. This makes sure that the build tracker will still pick up a build if it gets aborted before it ever starts.

fixes #1585

### CODE REVIEW

**Comment by pivotal-jwinters** [comment]
@vito yeah makes sense. Seems to be a simple fix, since we already abort the build when it can't be started.

File: atc/db/worker_lifecycle.go [hunk 1]
```diff
@@ -80,14 +80,7 @@ func (lifecycle *workerLifecycle) DeleteFinishedRetiringWorkers() ([]string, err
 		Join("containers c ON b.id = c.build_id").
 		Join("workers w ON w.name = c.worker_name").
 		LeftJoin("jobs j ON j.id = b.job_id").
-		Where(sq.Or{
-			sq.Eq{
-				"b.status": string(BuildStatusStarted),
-			},
-			sq.Eq{
-				"b.status": string(BuildStatusPending),
```
Comment (vito) [inline atc/db/worker_lifecycle.go]: Come to think of it I wonder if we ever needed to even check for pending builds. Why would a pending build have a container? :thinking:

File: atc/db/migration/migrations/1554304383_add_aborted_to_builds.up.sql [hunk 2]
```diff
@@ -0,0 +1,7 @@
+BEGIN;
+
+  ALTER TABLE builds ADD COLUMN aborted boolean DEFAULT false NOT NULL;
+
+  UPDATE builds SET aborted = true, completed = true WHERE status = 'aborted';
```
Comment (vito) [inline atc/db/migration/migrations/1554304383_add_aborted_to_builds.up.sql]: :+1: this is important so that old builds that were aborted but not completed don't gum up the API and make it think it's the 'next build'
