### PR TITLE
Avoid stale prometheus worker metrics when using multiple web nodes

### LINKED ISSUE #6956: Prometheus metric concourse_workers_containers falsely stuck on maximum value
## Summary

The Prometheus metric `concourse_workers_containers` was falsely stuck on the maximum value, and not reporting for all workers. Restarting the web Kubernetes pods "unstuck" the reported metric.

## Steps to reproduce

Sorry, no idea! Logs don't seem to show anything.

## Expected results

The correct values reported in real time.

## Actual results

Grafana dashboard showing the stuck metric:
image

Querying the exporter directly and seeing the stuck metric:
image

## Additional context
One of the `web` pods was fresh, the rest were old:
image

## Triaging info

* Concourse version: 5.8.1
* Browser (if applicable): N/A
* Did this used to work? N/A

### PR DESCRIPTION
**Pull request by databus23**
## Changes proposed by this PR

closes #6956

The reasoning for this PR are explained in this comment: https://github.com/concourse/concourse/issues/6956#issuecomment-1012005398

### CODE REVIEW

**Comment by databus23** [comment]
@xtremerui Can we pull this in the 7.7 milestone. It fixes a bug

File: atc/metric/emitter/prometheus.go [hunk 1]
```diff
@@ -1312,7 +1300,7 @@ func (emitter *PrometheusEmitter) periodicMetricGC() {
 		emitter.mu.Lock()
 		now := time.Now()
 		for worker, lastSeen := range emitter.workerLastSeen {
-			if now.Sub(lastSeen) > 5*time.Minute {
+			if now.Sub(lastSeen) > 2*time.Minute {
```
Comment (xtremerui) [inline atc/metric/emitter/prometheus.go:1303]: Is there a reason to reduce the GC period from 5 to 2 mins here?

**Review by xtremerui — COMMENTED** [review]
Thx for spending time and digging it out! We'd happy to include it in 7.7.
