### PR TITLE
algorithm: fix pagination of rerun builds, add tracing

### LINKED ISSUE #5094: Implement tracing for the algorithm
* [x] Trace algorithm recursion and etc. through the various resolvers
* [x] Trace spans or events for when incremental migrations are performed

### PR DESCRIPTION
**Pull request by vito**
# Existing Issue

Fixes #5094.

The actual bugfix here isn't captured in a separate issue, but there is (some) context in https://github.com/concourse/concourse/issues/5063#issuecomment-580271863.

# Why do we need this PR?

A bug with the algorithm's pagination logic (used for walking over chunks of 100 builds at a time) caused it to get stuck in a loop when looking for builds prior to a rerun.

This PR slings a bunch of code around in service of introducing tracing, which allowed this issue to be discovered and diagnosed pretty easily!

# Changes proposed in this pull request

* fix pagination bug
* backfill unit tests for `VersionsDB` covering this scenario and a few others
* introduce tracing, and the ability to use tracing for algorithm tests
* threads `ctx` through `VersionsDB` and uses it to trace the incremental migrations
* adds support for `context.Context` in our `db.Conn` interface, though we don't actually make use of it yet (for e.g. canceling in flight queries). just figured I'd add this along the way.

# Contributor Checklist

- [x] Unit tests
- [ ] Integration tests (if applicable)
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

File: atc/db/versions_db.go [hunk 1]
```diff
@@ -623,30 +590,73 @@ func (versions VersionsDB) migrateSingle(buildID int) (string, error) {
...
 
+type BuildCursor struct {
+	ID      int
+	RerunOf sql.NullInt64
+}
+
+func (cursor BuildCursor) OlderBuilds(idCol string) sq.Sqlizer {
+	if cursor.RerunOf.Valid {
+		return sq.Or{
+			sq.Expr("COALESCE(rerun_of, "+idCol+") < ?", cursor.RerunOf.Int64),
```
Comment (clarafu) [inline atc/db/versions_db.go]: I think this won't catch the original build of a rerun (ex, if there are builds 5.1 and 5, it won't grab build 5 if the cursor is 5.1). Do we care about grabbing all the builds that are all reruns of each other? Since they all have the same input versions? Maybe we only care about grabbing latest rerun of a build?

File: atc/db/versions_db.go [hunk 2]
```diff
@@ -623,30 +590,73 @@ func (versions VersionsDB) migrateSingle(buildID int) (string, error) {
...
+	if cursor.RerunOf.Valid {
+		return sq.Or{
+			sq.Expr("COALESCE(rerun_of, "+idCol+") > ?", cursor.RerunOf.Int64),
+			sq.And{
+				sq.Eq{"rerun_of": cursor.RerunOf.Int64},
+				sq.Gt{idCol: cursor.ID},
+			},
+		}
+	} else {
+		return sq.Expr("COALESCE(rerun_of, "+idCol+") > ?", cursor.ID)
```
Comment (clarafu) [inline atc/db/versions_db.go]: I think this won't catch the rerun builds if the cursor is on the original build. For example, if we have builds 5.2, 5.1, 5 and the cursor id is 5, any reruns of that build will have a rerun_of of 5 (5.1 and 5.2 will have rerun_of = 5) so they won't be fetched from this query because we only grab anything larger than the cursor ID.

File: atc/db/versions_db.go (hunk 1 above)
Comment (vito) [reply atc/db/versions_db.go]: > I think this won't catch the original build of a rerun (ex, if there are builds 5.1 and 5, it won't grab build 5 if the cursor is 5.1).

Good catch - I'll add a test for this!

> Do we care about grabbing all the builds that are all reruns of each other? Since they all have the same input versions? Maybe we only care about grabbing latest rerun of a build?

Thought about this - I think we do, because while they all have the same inputs they might end up having different outputs.

File: atc/db/versions_db.go (hunk 2 above)
Comment (vito) [reply atc/db/versions_db.go]: > I think this won't catch the rerun builds if the cursor is on the original build. For example, if we have builds 5.2, 5.1, 5 and the cursor id is 5, any reruns of that build will have a rerun_of of 5 (5.1 and 5.2 will have rerun_of = 5) so they won't be fetched from this query because we only grab anything larger than the cursor ID.

:+1: will add a test
