### PR TITLE
worker: Fix flakey container sweeper test

### LINKED ISSUE #5174: flaky container sweeper test
### What challenge are you facing?

Most of the times that `unit` failed, it's been because of a specific test:

```
• Failure [60.175 seconds]

Container Sweeper when garden doesn't respond on DELETE [It] request to garden times out eventually 

/tmp/build/0df9eea0/concourse/worker/container_sweeper_test.go:125

  Method mismatch

  Expected
      <string>: GET

  to equal
      <string>: DELETE

---


{"timestamp":"1580837223.526484728","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1196"}}
{"timestamp":"1580837223.576495409","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1197"}}
{"timestamp":"1580837223.626579762","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1198"}}
{"timestamp":"1580837223.676609993","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1199"}}
{"timestamp":"1580837223.727622747","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1200"}}
{"timestamp":"1580837223.777297735","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1201"}}
{"timestamp":"1580837223.828325033","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1202"}}
{"timestamp":"1580837223.877239704","source":"container-sweeper","message":"container-sweeper.tick.failed-to-list-containers","log_level":2,"data":{"error":"bad response: EOF","session":"1203"}}

```

(e.g., https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/97)

https://github.com/concourse/concourse/blob/1bf7c3ca37ef6ac707b36b8909abc698b1287063/worker/container_sweeper_test.go#L125-L127

### What would make this better?

Have the test not flaky as it currently is

### PR DESCRIPTION
**Pull request by xtreme-vikram-yadav**
Co-authored-by: Rui Yang <ryang@pivotal.io>

## What does this PR accomplish?
Fixes flakey container sweeper test by increasing sweeper timeout to 1sec. for tests.

We set the timeout to 500MS but it failed at 190th run. We arte setting it to 1 sec. just to be on safer side.

closes #5174 .

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

File: worker/container_sweeper_test.go [hunk 1]
```diff
@@ -125,7 +125,7 @@ var _ = Describe("Container Sweeper", func() {
 		It("request to garden times out eventually", func() {
 			Eventually(testLogger.Buffer()).Should(gbytes.Say("failed-to-destroy-container\".*\\(Client.Timeout exceeded while awaiting headers\\)"))
 		})
-		It("sweeper continues ticking and GC'ing", func() {
+		FIt("sweeper continues ticking and GC'ing", func() {
```
Comment (aoldershaw) [inline worker/container_sweeper_test.go:128]:
```suggestion
		It("sweeper continues ticking and GC'ing", func() {
```

also, missing DCO
