### PR TITLE
web: Refactor scrolling and reduce build page API calls

### LINKED ISSUE #3044: build page gradually fetches all builds until the beginning of time
## Bug Report

When loading the build page for a job that has many builds, a huge number of (often-unvaluable) API calls are made.

## Steps to Reproduce

1. Open the build page for a job with many builds, e.g. https://ci.concourse-ci.org/teams/main/pipelines/monitoring-stats/jobs/create-and-run-new-pipeline/builds/305743.
1. Look at the Network tab in Developer Tools.

## Expected Results

The number of API calls settles down. The only ongoing network activity should be from the stream of events for a running build.

## Actual Results

many many calls to the builds endpoint:
screen shot 2019-01-14 at 11 25 27 am

## Additional Context

On busy web nodes and/or on clusters with huge build tables, needlessly hammering the builds endpoint could be fatal.

## Version Info

* Concourse version: 5.0.0 (master)
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? I don't think so

### LINKED ISSUE #3431: Refactor Scroll to use ports instead of an effect manager
Splitting out a sub-task of #3155.

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
Branched from #3428, please merge it first.

Fixes #3044 
Fixes #3431

### CODE REVIEW

File: web/elm/src/Build/Build.elm [hunk 1]
```diff
@@ -92,59 +94,73 @@ init flags =
...
-    , OnKeyPress KeyPressed
+    let
+        buildEventsUrl =
+            model.currentBuild
+                |> RemoteData.toMaybe
+                |> Maybe.andThen .output
+                |> Maybe.andThen .eventStreamUrlPath
+    in
+    [ OnClockTick OneSecond
+    , OnScrollToBottom
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: Oooooh, much nicer name.

File: web/elm/src/Build/Build.elm [hunk 2]
```diff
@@ -199,206 +224,249 @@ getUpdateMessage model =
...
+                        , hoveredCounter = model.hoveredCounter + 1
+                    }
+            in
+            updateOutput
+                (Build.Output.Output.handleStepTreeMsg <|
+                    StepTree.updateTooltip newModel
+                )
+                ( newModel, effects )
+
+        ScrolledToBottom atBottom ->
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: And you did the "just make it a damn boolean" refactor too. Nice.

File: web/elm/src/Build/Build.elm [hunk 3]
```diff
@@ -199,206 +224,249 @@ getUpdateMessage model =
...
+
+                        NoScroll ->
+                            effects
+                    )
+
+        ElementVisible id isVisible ->
+            let
+                lastBuildId =
+                    model.history
+                        |> List.reverse
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: I think List.Extras has a `last`, which is clearer and probably more efficient than `reverse >> head`, but that's just a nitpick.

File: web/elm/src/Build/Build.elm [hunk 4]
```diff
@@ -199,206 +224,249 @@ getUpdateMessage model =
...
+                        |> Maybe.map .id
+                        |> Maybe.map toString
+
+                currentBuildId =
+                    model.currentBuild
+                        |> RemoteData.toMaybe
+                        |> Maybe.map .build
+                        |> Maybe.map .id
+            in
+            ( model
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: Ungh. This is correct, obviously, but I feel like `case of ... (model, effects) ... (model, effects)` reads better than `(model, case of ... effects ... effects)`, especially when the case is thirty lines long. Or pull out `let effects = .... in (model, effects)`, at least.

Comment (xtreme-james-cooper) [reply web/elm/src/Build/Build.elm]: Especially when, as here, there are only really two "interesting" cases and a whole bunch of "pass the accumulator".

File: web/elm/src/Build/Build.elm [hunk 5]
```diff
@@ -199,206 +224,249 @@ getUpdateMessage model =
...
-            case Char.fromCode keycode of
-                'T' ->
-                    ( { model | previousTriggerBuildByKey = False }, [] )
+                    else
+                        [ Scroll (Element "builds" -event.deltaX) ]
 
-                _ ->
-                    ( model, [] )
+                checkVisibility =
+                    case model.history |> List.reverse |> List.head of
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: Same last here, and it's model.history again. We... don't have any easy way of holding a pointer to the last element, because immutable copying lists :( But probably there's *some* way of cleaning this up, even if it's just a `lastBuild : Model -> Maybe Build` utility in the file somewhere.

File: web/elm/src/Build/Build.elm [hunk 6]
```diff
@@ -637,86 +702,91 @@ pollUntilStarted browsingIndex buildId =
...
+            }
     in
-    case
-        ( history.pagination.nextPage
-        , currentBuild |> Maybe.andThen (.job << .build)
-        )
-    of
-        ( Nothing, _ ) ->
-            ( withBuilds, [] )
+    ( newModel
```
Comment (xtreme-james-cooper) [inline web/elm/src/Build/Build.elm]: Still not a fan ;P

File: web/elm/src/Effects.elm [hunk 7]
```diff
@@ -65,6 +64,33 @@ port saveToken : String -> Cmd msg
 port requestLoginRedirect : String -> Cmd msg
 
 
+port openEventStream : { url : String, eventTypes : List String } -> Cmd msg
+
+
+port closeEventStream : () -> Cmd msg
+
+
+port scrollIntoView : String -> Cmd msg
```
Comment (xtreme-james-cooper) [inline web/elm/src/Effects.elm]: Ooooh nice, ports! ;)

File: web/elm/src/Effects.elm [hunk 8]
```diff
@@ -120,19 +146,22 @@ type Effect
...
-    = ToWindowTop
+    = ToTop
     | Down
     | Up
-    | ToWindowBottom
-    | Builds Float
-    | ToCurrentBuild
+    | ToBottom
+    | Element String Float
+    | ToBuild Int
```
Comment (xtreme-james-cooper) [inline web/elm/src/Effects.elm]: `ToBuild` now seems a bit overspecific, although I can see the argument for not moving it yet.

File: web/elm/src/Native/Scroll.js [hunk 9]
```diff
@@ -1,61 +0,0 @@
-var _concourse$atc$Native_Scroll = function() {
```
Comment (xtreme-james-cooper) [inline web/elm/src/Native/Scroll.js]: Awww yeah, blowing up native code 😎

File: web/elm/src/Scroll.elm [hunk 10]
```diff
@@ -1,169 +0,0 @@
-effect module Scroll where { subscription = MySub } exposing
```
Comment (xtreme-james-cooper) [inline web/elm/src/Scroll.elm]: Aw yeah, blowing up native modules 😎

File: web/elm/tests/BuildTests.elm [hunk 11]
```diff
@@ -573,7 +990,7 @@ all =
                     , mouseLeaveMsg = Build.Msgs.Hover Nothing
                     }
                 ]
-            , describe "when history and details witche dwith maual triggering disabled" <|
+            , describe "when history and details fetched with manual triggering disabled" <|
```
Comment (xtreme-james-cooper) [inline web/elm/tests/BuildTests.elm]: Wow. That's... uh... quite some spelling.

**Comment by marco-m** [comment]
wow thanks for this @pivotal-jamie-klassen !
