### PR TITLE
fix #8268 acrossStep handling for more then 3 vars

### LINKED ISSUE #8268: acrossStep with multiple vars/values isn't creating a full matrix
## Summary

We want to use the acrossStep with 6 vars each with 1 to 4 values. Concourse isn't creating a full matrix, its just using the last values of some of our vars.

## Steps to reproduce

```yaml
- across:
    - var: a
      values: ["a1"]
    - var: b
      values: ["b1", "b2"]
    - var: c
      values:
        ["c1", "c2", "c3", "c4"]
      max_in_flight: all
    - var: d
      values: ["d1", "d2"]
    - var: e
      values: ["e1", "e2"]
    - var: f
      values: ["f1", "f2"]
  do:
    - task: test
```

```go
package main

import (
	"fmt"
)

func cartesianProduct(varValues [][]interface{}) [][]interface{} {
	if len(varValues) == 0 {
		return make([][]interface{}, 1)
	}
	var product [][]interface{}
	subProduct := cartesianProduct(varValues[:len(varValues)-1])
	for _, vec := range subProduct {
		for _, val := range varValues[len(varValues)-1] {
			product = append(product, append(vec, val))
		}
	}
	return product
}

func main() {
	var matrix [][]interface{}
	matrix = append(matrix,
		append(make([]interface{}, 0), "a1"),
		append(make([]interface{}, 0), "b1", "b2"),
		append(make([]interface{}, 0), "c1", "c2", "c3", "c4"),
		append(make([]interface{}, 0), "d1", "d2"),
		append(make([]interface{}, 0), "e1", "e2"),
		append(make([]interface{}, 0), "f1", "f2"),
	)
	fmt.Printf("Underlying Value: %v\n", cartesianProduct(matrix))
}

```

## Expected results
To have a full matrix from a combination of all values

## Actual results
d1 and f1 are never used, but we have the correct count of items.
```
[[a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e2 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e2 f2]]
```

## Additional context

- https://stackoverflow.com/questions/16248241/concatenate-two-slices-in-go
- https://yourbasic.org/golang/gotcha-append/

## Triaging info

* Concourse version: 7.7.1
* Browser (if applicable):
* Did this used to work?

### PR DESCRIPTION
**Pull request by nexeck**
"If there is room for more elements, append reuses the underlying array."

Signed-off-by: Marcel Beck <marcel@beck.im>

[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR

closes #8268 

* [x] done
* [ ] todo

## Release Note

* 

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

### CODE REVIEW

**Comment by xtremerui** [comment]
Hi, thank you for the PR. 

There is test failure here https://ci.concourse-ci.org/builds/402760678. More specifically, the across step test is hanging and timing out.

**Comment by nexeck** [comment]
I do not have access to those build logs, can you give me access to them?
Is it just running `ginkgo -r -p` ?

Will try to reproduce this tomorrow locally.

**Comment by taylorsilva** [comment]
You can run all these tests under `./atc`. It keeps timing out on the `exec` suite tests. So you can probably focus on whatever test is failing under `./atc/exec`

image

**Comment by taylorsilva** [comment]
I think you have to join the contributors team to see build logs https://github.com/concourse/governance/

File: atc/exec/across_step_test.go [hunk 1]
```diff
@@ -304,7 +374,7 @@ var _ = Describe("AcrossStep", func() {
 				Expect(ok).To(BeFalse())
 
 				By("ensuring not all steps were started")
-				Expect(started).ToNot(HaveLen(12))
+				Expect(started).ToNot(HaveLen(24))
 			})
```
Comment (chenbh) [inline atc/exec/across_step_test.go:378]: This test will hang forever. Because new elements were added to the `allVals` [array above](https://github.com/concourse/concourse/pull/8271/files#diff-48f60c9a9abecfb45a8c06695920f378782827b0c4bc81dc3a92c66e17d6c446R238-R241), this test case is now trying to terminate the `{"a1", "b1", "c1", "d2"}` step, but this step is not part of the first stage and so the the steps there will never terminate.

This can be fixed by changing line 369 to point to one of the vars combo that is executed in the first stage.

**Review by chenbh — CHANGES_REQUESTED** [review]

**Comment by nexeck** [comment]
I can't access the build logs from the CI System. Is the failing test related to my changes, or something else?

This is from my local machine:
image

**Review by chenbh — APPROVED** [review]
The failing test cases were due to that one test hanging and timing out but it's good to go now.

lgtm, thanks!
