### PR TITLE
Fix build reaper missing builds due to pagination

### LINKED ISSUE #5977: Build reaper misses builds if first logged id is after the first page
## Summary

The build log collector pagination logic is flawed such that if the number of builds between the `first_logged_build_id` and the most recent build for a job is > 500, it will not reap the `first_logged_build_id`

## Steps to reproduce

1. Set a pipeline with a job that has `build_log_retention.days = 1` (make sure it's the first pipeline to be created - the script to follow relies on job + pipeline + team IDs all being 1)
1. Run the following script:

```sh
# Pause the build reaper
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE components SET paused = true WHERE name = 'reaper';"

# Create 501 builds (1 more than the page size)
for i in `seq 1 501`; do
  PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "INSERT INTO builds(name, status, end_time, job_id, team_id, pipeline_id) VALUES ('$i', 'succeeded', now(), 1, 1, 1);"
done

# Set the end_time of the first build to before 1 day ago
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE builds SET end_time = now() - '2 days'::interval, completed = true WHERE name = '1';"

# Unpause the build reaper
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE components SET paused = false WHERE name = 'reaper';"
```

## Expected results

Eventually, the first build should get reaped

## Actual results

It never does

## Additional context

The `build-reaper` always logs:
```
web_1     | {"timestamp":"2020-08-11T18:21:06.632844500Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-first-round-filter","data":{"buildsToConsiderDeleting":500,"session":"25.119.2"}}
web_1     | {"timestamp":"2020-08-11T18:21:06.633361400Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-second-round-filter","data":{"retainedBuilds":0,"retainedSucceededBuilds":0,"session":"25.119.2"}}
```

Note how `buildsToConsiderDeleting` is only 500 - it should be 501, I believe

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable):
* Did this used to work?

### PR DESCRIPTION
**Pull request by chenbh**
## What does this PR accomplish?
**Bug Fix** | Feature | Documentation

closes #5977 

## Changes proposed by this PR:

Since/until used to be chronologically right to left, they're replaced by from/to which is now chronologically left to right:

Given we have build ids: `1, 2, 3, 4, 5, 6, 7`
`since=4` would give us: `3, 2, 1` and `until=4` would give: `7, 6, 5`
`from=4` would give us: `7, 6, 5, 4` and `to=4` would give: `4, 3, 2, 1`

- replace since/until with from/to in atc, go-concourse, and web (fly keeps it as it's used in different meaning there)
- from/to are now int pointers to differentiate between default value `nil`, and explicit `0`
- as a result of above changes, build reaper no longer misses builds
- fixed the left chevron always directing to the starting page for resource versions and job builds page
- fixed edge case where the left chevron would lead to 

## Notes to reviewer:
Reviewing commit by commit is probably better

## Release Note
- Fixed the build reaper missing builds
- Fixed pagination bugs on the resource version and job builds pages

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] ~Updated [Documentation]~
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Review by taylorsilva — APPROVED** [review]
Ran the reproducible steps from @aoldershaw  on `master` and then on this PR. Got the expected 501 builds deleted with this PR:
```
web_1     | {"timestamp":"2020-09-11T14:55:44.757854400Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-first-round-filter","data":{"buildsToConsiderDeleting":501,"session":"25.9.2"}}
web_1     | {"timestamp":"2020-09-11T14:55:44.758021800Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-second-round-filter","data":{"retainedBuilds":0,"retainedSucceededBuilds":0,"session":"25.9.2"}}
```

I did acceptance on:
- builds page
- versions page
- API endpoints that changed

Everything worked as expected! Pages paginated as expected and I didn't notice anything funky happen. I like the simplification to `from/to`. 
I'm approving (I can approve again once `unit` passes. yarn-analyze found something?) though I'm not confident about my evaluation of the elm code. It all seems fine though! 😬

File: web/elm/src/Resource/Resource.elm [hunk 1]
```diff
@@ -789,12 +805,12 @@ permalink : List Concourse.VersionedResource -> Page
 permalink versionedResources =
```
Comment (taylorsilva) [inline web/elm/src/Resource/Resource.elm:805]: This is unused

```
Messages:

- src/Resource/Resource.elm

  > Unused top level definition `permalink` at ((805,1),(805,10))

error Command failed with exit code 1.                                         

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Did a quick check:
```
┌─[issue/5977*][~/workspace/concourse/concourse/web/elm]
└─▪ ag 'permalink'
src/Job/Job.elm
302:permalink : List Concourse.Build -> Page
303:permalink builds =
379:            permalink paginatedBuilds.content

src/Resource/Resource.elm
804:permalink : List Concourse.VersionedResource -> Page
805:permalink versionedResources =
```

Comment (chenbh) [reply web/elm/src/Resource/Resource.elm]: Fixed!

**Review by taylorsilva — APPROVED** [review]
