### PR TITLE
web: show most-privileged role on team pills

### LINKED ISSUE #4399: Concourse UI sometimes don't choose the role with highest level of permission
## Bug Report

Concourse UI sometimes don't choose the owner's role if you logged in with several GitHub teams.

## Steps to Reproduce

- Login into UI using GitHub account with several teams.
- Check `fly userinfo`:
```
concourse $ fly logout -a
logged out of all targets
concourse $ fly -t devops-core@ci/devops userinfo
could not find a valid token.
logging in to team 'devops'

navigate to the following URL in your browser:

  https://ci.concourse.net/login?fly_port=50700

target saved
username    team/role                                                                                                            
golubovsky  cloud-dev/owner,cloud-prod/owner,cloud-prod/pipeline-operator,development/owner,devops/member,devops/owner,main/owner
concourse $
```
In the output I see that I have the owner role for all teams
## Expected Results

I expect to see the same in UI - the owner of all.

## Actual Results

Actually, for some reason, I see only the member role for one of the teams (devops).
Screenshot - https://prnt.sc/p4ac1p

## Additional Context

`devops.yaml` used for configuration:
```
roles:
- name: owner
  local:
    users: ["devops-core"]
  github:
    teams: ["my-org:devops-core"]
- name: member
  local:
    users: ["devops", "dev-core"]
  github:
    teams: ["my-org:devops", "my-org:devs-core"]
- name: viewer
  local:
    users: ["dev"]
  github:
    teams: ["my-org:devs"]
```

Configured teams:
```
concourse $ fly -t devops-core@ci/devops teams -d
name/role                      users                           groups                                                              
cloud-dev/member               local:dev-core                  github:my-org:devs-core                                  
cloud-dev/owner                local:devops-core,local:devops  github:my-org:devops-core,github:my-org:devops
cloud-dev/pipeline-operator    local:dev                       github:my-org:devs                                       
cloud-prod/owner               local:devops-core               github:my-org:devops-core                                
cloud-prod/pipeline-operator   local:devops,local:dev-core     github:my-org:devops,github:my-org:devs-core  
cloud-prod/viewer              local:dev                       github:my-org:devs                                       
development/member             local:dev-core                  github:my-org:devs-core                                  
development/owner              local:devops-core,local:devops  github:my-org:devops-core,github:my-org:devops
development/pipeline-operator  local:dev                       github:my-org:devs                                       
devops/member                  local:devops,local:dev-core     github:my-org:devops,github:my-org:devs-core  
devops/owner                   local:devops-core               github:my-org:devops-core                                
devops/viewer                  local:dev                       github:my-org:devs                                       
main/owner                     local:devops-core               github:my-org:devops,github:my-org:core       
concourse $ 
```

Other users see the same issue, but with other teams (they have other set of GitHub teams).

## Version Info

* Concourse version: 5.5.0 (also was in 5.4.1)
* Deployment type (BOSH/Docker/binary): Docker
* Did this used to work? yes

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
# Existing Issue

Fixes #4399.

# Changes proposed in this pull request

It's possible to configure a team's auth such that a single user might have multiple roles - for example, if you grant "viewer" status to all members of a GitHub org, but "member" status to members of a specific GitHub team within that org. The UI only shows a single role in the pills on the team headers on the dashboard. The choice of which role to show was, until now, determined by whatever the API put first in the list of roles returned by the userinfo endpoint.

Users have justifiably found this confusing or misleading, and it generally seems sensible to show the most-privileged role a user has on any given team, since roles are in a strict hierarchy and the most-privileged role will be the one that determines the actions a user is authorized to take. 

With this change, the UI will make sure it displays the most-privileged role in the pills.

# Contributor Checklist
- [x] Unit tests
- [x] ~Integration tests (if applicable)~
- [x] ~Updated documentation (located at https://github.com/concourse/docs)~
- [x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [x] Code reviewed
- [x] Tests reviewed
- [x] ~Documentation reviewed~
- [x] Release notes reviewed
- [ ] PR acceptance performed
- [x] ~New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).~

### CODE REVIEW

File: web/elm/tests/DashboardTests.elm [hunk 1]
```diff
@@ -1026,12 +1026,16 @@ all =
                         |> Tuple.first
                         |> Common.queryView
                         |> teamHeaderHasNoPill "team"
-            , test "shows pill for first role on team header for team on which user has multiple roles" <|
+            , test
+                ("shows pill for most-privileged role on team header for team"
+                    ++ "on which user has multiple roles"
```
Comment (aoldershaw) [inline web/elm/tests/DashboardTests.elm]: Really minor nit, but there should probably be a space between "team" and "on"

Comment (pivotal-jamie-klassen) [reply web/elm/tests/DashboardTests.elm]: heck yeah there should. i obviously didn't watch that test fail! (I did, but only before I changed the text, thus making The Diagnostics worse lol)

**Comment by jomsie** [comment]
(it also L good TM!)
