### PR TITLE
switch to pure go impl of zstd

### LINKED ISSUE #4621: fly execute sometimes returns 500 error when loading an input directory containing a terraform state file
## Bug Report

We were trying to run `fly execute -i terraform-state-file=$TERRAFORM_PATH` and we receive 500 errors around 80% of the time because it fails to upload the input directory. The other 20% of the time, the input directory uploads successfully.

## Steps to Reproduce

1. Run Concourse on Kubernetes.

1. Deploy Ops Manager on AWS  using terraform by following the instructions here: https://docs.pivotal.io/pivotalcf/2-6/om/aws/prepare-env-terraform.html

1. After deploying Ops Manager, you should end up with a `terraform.tfstate` file.

1. Put this `terraform.tfstate` file in an empty directory.

1. Use this directory as an input into a Concourse task (for example, name it `terraform-state-file`).

1. Run `fly execute -i terraform-state-file=$PATH_TO_DIRECTORY_ABOVE`.

## Expected Results

Input directory should upload successfully and say "Done".

## Actual Results

Uploading fails 80% of the time with 500 error.

## Additional Context

Does not happen with Bosh-deployed Concourse, error only occurs with Kubernetes-deployed Concourse.

We found a workaround for this issue. By creating a copy of the input directory inside the input directory, it uploads successfully 100% of the time. More specifically:

This **doesn't work**:
```
terraform-state-file/
|-- terraform.tfstate
```

This **does work**:
```
terraform-state-file/
|-- terraform.tfstate
|-- terraform-state-file/
    |-- terraform.tfstate
```

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): Kubernetes (Helm)
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Not sure.

### PR DESCRIPTION
**Pull request by kcmannem**
Signed-off-by: Alex Suraci <asuraci@pivotal.io>
Co-authored-by: Krishna Mannem <kmannem@pivotal.io>

Fixes #4621

# Changes proposed in this pull request

* converts datadog/zstd dependency to klauspost/compress/zstd

# Contributor Checklist
- [x] Unit tests
- [x] Integration tests (if applicable)
- [x] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

File: atc/worker/artifact_source.go [hunk 1]
```diff
@@ -111,6 +114,18 @@ func (source *cacheArtifactSource) ExistsOn(logger lager.Logger, worker Worker)
...
 }
 
+type CloseWithError struct {
+	NoErringCloser interface {
+		Close()
+	}
+}
+
+// I know this is bad
+func (cwe CloseWithError) Close() error {
```
Comment (kcmannem) [inline atc/worker/artifact_source.go]: the new zstd reader does not follow io.Closer { Close() error} but rather just has Close() with no error. I had to wrap it so that it can be passed to fileReadMultiCloser.closers[]

I'm open to suggestions on this.

File: fly/commands/internal/executehelpers/uploads.go [hunk 2]
```diff
@@ -19,7 +19,18 @@ func Upload(bar *mpb.Bar, team concourse.Team, path string, includeIgnored bool,
 	archiveStream, archiveWriter := io.Pipe()
 
 	go func() {
-		archiveWriter.CloseWithError(tarfs.Compress(zstd.NewWriter(archiveWriter), path, files...))
+		zstdWriter, err := zstd.NewWriter(archiveWriter)
+		if err != nil {
+			return
```
Comment (kcmannem) [inline fly/commands/internal/executehelpers/uploads.go]: should we bubble this err up?

File: go.mod [hunk 3]
```diff
@@ -126,4 +127,6 @@ require (
 
 go 1.13
 
+replace github.com/concourse/baggageclaim => ./baggageclaim
```
Comment (cirocosta) [inline go.mod]: whoops? 🤔

**Comment by kcmannem** [comment]
Gotta merge https://github.com/concourse/baggageclaim/pull/34 and then bump go mod as well

File: fly/commands/internal/executehelpers/uploads.go (hunk 2 above)
Comment (cirocosta) [reply fly/commands/internal/executehelpers/uploads.go]: I think if we close the pipe's writer with the error here, we might end up already propagating it from what I got - when doing `archiveWriter.CloseWithError(err)`, that gets stored, and then subsequently a `read` on the other side would notice that it's closed, and then bring the error.

(didn't verify that myself)

File: fly/commands/internal/executehelpers/uploads.go [hunk 4]
```diff
@@ -18,8 +18,20 @@ func Upload(bar *mpb.Bar, team concourse.Team, path string, includeIgnored bool,
 
 	archiveStream, archiveWriter := io.Pipe()
 
+	zstdWriter, err := zstd.NewWriter(archiveWriter)
+	if err != nil {
+		return atc.WorkerArtifact{}, err
+	}
+
 	go func() {
```
Comment (kcmannem) [inline fly/commands/internal/executehelpers/uploads.go]: @cirocosta updated

Comment (cirocosta) [reply fly/commands/internal/executehelpers/uploads.go]: thaanks!

**Comment by cirocosta** [comment]
Hey,

I just finished fixing some conflicts.

Should be good to go after tests run.

**Comment by pivotal-izabela-gomes** [comment]
We are seeing some tests failing from testflight suite when running concourse and baggage claim with the new impl. So, we are going to investigate further. We saw 8 failures in one run and 2 in another subsequent one.
```
Summarizing 8 Failures:

[Fail] Flying [Measurement] works
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying hijacking [Measurement] executes an interactive command in a running task's container
/Users/pivotal/workspace/concourse/testflight/flying_test.go:99

[Fail] Flying uploading inputs with and without --include-ignored [Measurement] uploads git repo input and non git repo input, IGNORING things in the .gitignore for git repo inputs
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying uploading inputs with and without --include-ignored [Measurement] uploads git repo input and non git repo input, INCLUDING things in the .gitignore for git repo inputs
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying pulling down outputs [Measurement] works
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying aborting [Measurement] terminates the running task
/Users/pivotal/workspace/concourse/testflight/flying_test.go:232

[Fail] Flying when an optional input is not provided [Measurement] runs the task without error
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying when the input is custom resource when -j is not specified and local input in custom resource type is provided [Measurement] runs the task without error
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213
```

```
Summarizing 2 Failures:

[Fail] Flying with an image_resource [Measurement] propagates the rootfs and metadata to the task
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213

[Fail] Flying with an image_resource [Measurement] allows a version to be specified
/Users/pivotal/workspace/concourse/testflight/suite_test.go:213
```

**Comment by xtreme-sameer-vohra** [comment]
We still have a bunch of refs to `github.com/DataDog/zstd` remaining in the repo

```
ag "DataDog/zstd"

go.mod
11:	github.com/DataDog/zstd v1.4.0

fly/integration/execute_with_outputs_test.go
14:	"github.com/DataDog/zstd"

fly/integration/execute_overriding_inputs_test.go
13:	"github.com/DataDog/zstd"

fly/integration/execute_multiple_inputs_test.go
14:	"github.com/DataDog/zstd"

fly/integration/execute_test.go
19:	"github.com/DataDog/zstd"

fly/commands/internal/executehelpers/downloads.go
4:	"github.com/DataDog/zstd"
```

**Comment by xtreme-sameer-vohra** [comment]
Was able to run testflight successfully though, so thats not an issue anymore

**Comment by xtreme-sameer-vohra** [comment]
Hey @vito @cirocosta 
Do y'all have context on this issue. Thinking of moving it back to the `Todo` column in side-road to be re-prioritized during IPM

**Comment by cirocosta** [comment]
Hey @xtreme-sameer-vohra 

I think the problem in your setup is the `fly -t TARGET sync -f` - doing that, you'll not have the version of `fly` that's been patched 🤔  

Here, I get success when having `fly` built from this branch (`go install -v ./fly`), and failure when I build fly from `master`.
