### PR TITLE
Fixed build log reaper not respecting when both Days and Builds are set

### LINKED ISSUE #7130: Build logs appear to be reaped against retention settings
## Summary

We have a concourse cluster with the following configuration values set:
CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN = 50
CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS = 30

**Note:** The CONCOURSE_MAX_BUILD_LOGS_TO_RETAIN and CONCOURSE_MAX_DAYS_TO_RETAIN_BUILD_LOGS are not set and nor are any job specific retention policies being applied.

One of our pipelines runs infrequently and only has 5 runs in total, however the last run was over 30 days ago and all the build logs for the previous runs for that job have been reaped.

The documentation at https://concourse-ci.org/concourse-web.html#build-log-retention states that:

> CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN=50
> CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS=14
> With these settings, Concource will keep the latest 50 builds for each job. If a job runs more than 50 builds in 14 days, all of those builds will be retained until 14 days after they ran.

Which suggests that build logs should not be reaped until both criteria are met, however our experience above shows that the CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS criteria seems to override the CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN criteria so either there is a bug in the cleanup process or the documentation is unclear.

## Steps to reproduce

1. Deploy Concourse with the following env variables set to non-zero values:
CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN
CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS
2. Run multiple pipeline jobs to create some build history, but do not exceed the CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN value
3. Wait for the number of days defined in CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS to elapse

## Expected results

No logs to be reaped as they are still within the CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN criteria

## Actual results

All logs exceeding the CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS  criteria are reaped

## Additional context

N/A

## Triaging info

* Concourse version: 6.7.4
* Browser (if applicable): N/A
* Did this used to work? Don't know as only recently enabled the retention settings

### PR DESCRIPTION
**Pull request by EstebanFS**
## Changes proposed by this PR

closes #7130.

## Release Note

- The build log reaper has two options for determining when to reap logs. Before, if both of the options are set, it would reap if either of the two options were true, rather than requiring *both* of them to be satisfied

### CODE REVIEW

File: atc/gc/build_log_collector.go [hunk 1]
```diff
@@ -156,26 +148,50 @@ func (br *buildLogCollector) reapLogsOfJob(pipeline db.Pipeline,
...
-		if logRetention.Builds > 0 {
-			if logRetention.MinimumSucceededBuilds > 0 && build.Status() == db.BuildStatusSucceeded {
-				if retainedSucceededBuilds < logRetention.MinimumSucceededBuilds {
-					retainedBuilds++
-					retainedSucceededBuilds++
-					firstLoggedBuildID = build.ID()
-					continue
-				}
+		// If the minimum is set but not satisfied it should not be reaped
+		if logRetention.Builds != 0 && logRetention.MinimumSucceededBuilds != 0 {
```
Comment (aoldershaw) [inline atc/gc/build_log_collector.go:152]: I feel like this logic can be simplified a little. All we really care about is that if any of the enabled conditions are *not* met, then we *don't* reap the build. So, what if we wrote it like this pseudocode:

```
if logRetention.Builds != 0 {
  if logRetention.MinimumSucceededBuilds != 0 {
    if build succeeded && haven't retained enough succeeded builds {
      retain(build)
      continue
    }
  }
  if haven't retained enough builds {
    retain(build)
  }
}

if logRetention.Days != 0 {
  if build has not expired {
    retain(build)
    continue
  }
}

// at this point, we haven't met all of the enabled conditions, so here we can reap
buildIDsToDelete = append(buildIDsToDelete, build.ID())
```

<details>

<summary>Some actual code to this effect</summary>

```diff
diff --git a/atc/gc/build_log_collector.go b/atc/gc/build_log_collector.go
index f0ac616a5..91b3e8a6d 100644
--- a/atc/gc/build_log_collector.go
+++ b/atc/gc/build_log_collector.go
@@ -133,6 +133,18 @@ func (br *buildLogCollector) reapLogsOfJob(pipeline db.Pipeline,
 	retainedBuilds := 0
 	retainedSucceededBuilds := 0
 	firstLoggedBuildID := 0
+
+	retain := func(build db.Build) {
+		firstLoggedBuildID = build.ID()
+		retainedBuilds++
+		if build.Status() == db.BuildStatusSucceeded {
+			retainedSucceededBuilds++
+		} else if logRetention.Builds != 0 {
+			// only need to track if there's a limit on number of builds
+			toRetainNonSucceededBuildIDs = append(toRetainNonSucceededBuildIDs, build.ID())
+		}
+	}
+
 	for _, build := range buildsToConsiderDeleting {
 		// Running build should not be reaped.
 		if build.IsRunning() {
@@ -148,51 +160,29 @@ func (br *buildLogCollector) reapLogsOfJob(pipeline db.Pipeline,
 			}
 		}
 
-		// If the minimum is set but not satisfied it should not be reaped
-		if logRetention.Builds != 0 && logRetention.MinimumSucceededBuilds != 0 {
-			if build.Status() == db.BuildStatusSucceeded && retainedSucceededBuilds < logRetention.MinimumSucceededBuilds {
-				retainedBuilds++
-				retainedSucceededBuilds++
-				firstLoggedBuildID = build.ID()
-				continue
+		if logRetention.Builds != 0 {
+			if logRetention.MinimumSucceededBuilds != 0 {
+				if build.Status() == db.BuildStatusSucceeded && retainedSucceededBuilds < logRetention.MinimumSucceededBuilds {
+					retain(build)
+					continue
+				}
 			}
-		}
-
-		maxBuildsRetained := retainedBuilds >= logRetention.Builds
 
-		// If only builds is set
-		if logRetention.Days == 0 {
-			if maxBuildsRetained {
-				logger.Debug("should-reap-due-to-builds", build.LagerData())
-				buildIDsToDelete = append(buildIDsToDelete, build.ID())
-			} else {
-				retainedBuilds++
-				toRetainNonSucceededBuildIDs = append(toRetainNonSucceededBuildIDs, build.ID())
-				firstLoggedBuildID = build.ID()
+			if retainedBuilds < logRetention.Builds {
+				retain(build)
+				continue
 			}
-			continue
 		}
 
-		buildHasExpired := !build.EndTime().IsZero() && build.EndTime().AddDate(0, 0, logRetention.Days).Before(time.Now())
-
-		// If only Days is set
-		if logRetention.Builds == 0 {
-			if buildHasExpired {
-				logger.Debug("should-reap-due-to-days", build.LagerData())
-				buildIDsToDelete = append(buildIDsToDelete, build.ID())
+		if logRetention.Days != 0 {
+			buildHasExpired := !build.EndTime().IsZero() && build.EndTime().AddDate(0, 0, logRetention.Days).Before(time.Now())
+			if !buildHasExpired {
+				retain(build)
+				continue
 			}
-			continue
 		}
 
-		// If Builds and Days are set
-		if maxBuildsRetained && buildHasExpired {
-			logger.Debug("should-reap-due-to-days-and-builds", build.LagerData())
-			buildIDsToDelete = append(buildIDsToDelete, build.ID())
-		} else {
-			retainedBuilds++
-			toRetainNonSucceededBuildIDs = append(toRetainNonSucceededBuildIDs, build.ID())
-			firstLoggedBuildID = build.ID()
-		}
+		buildIDsToDelete = append(buildIDsToDelete, build.ID())
 	}
 
 	logger.Debug("after-second-round-filter", lager.Data{
@@ -207,7 +197,7 @@ func (br *buildLogCollector) reapLogsOfJob(pipeline db.Pipeline,
 
 	// If this happens, firstLoggedBuildID must points to a success build, thus
 	// no need to update firstLoggedBuildID.
-	if retainedBuilds > logRetention.Builds {
+	if logRetention.Builds != 0 && retainedBuilds > logRetention.Builds {
 		logger.Debug("more-builds-to-retain", lager.Data{
 			"retained_builds": retainedBuilds,
 		})
```
</details>

IMO it's a bit easier to understand since we can consider the rules around builds and days independently, rather than considering each permutation (Builds+Days, Builds, Days).

WDYT?

**Review by aoldershaw — APPROVED** [review]
