### PR TITLE
The Great Decoupling

### LINKED ISSUE #2826: Store user artifacts from fly execute in a volume
Currently when someone does a `fly execute` the API handler needs to coordinate user input streaming through the exec.Engine package. The `buidlserver` and `pipelineserver` in the below examples need to communicate through the same exec.Engine object so that they can transfer data over a channel.

https://github.com/concourse/concourse/blob/master/atc/api/buildserver/send_input.go#L61
https://github.com/concourse/concourse/blob/master/atc/api/pipelineserver/build.go#L39

We want to decouple the system by streaming user artifacts directly to a volume, and having the build plan grab those inputs from the volume.

### LINKED ISSUE #2895: Scheduler race condition resulting in skipped versions (mainly with `version: every`)
## Bug Report

This `testflight` test fails, if you run it enough times:

https://github.com/concourse/concourse/blob/c3896f1ecd34d1b340d876997c4e4c46b75c9c29/testflight/resource_version_test.go#L45

Here's a CI build showing the failure: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/273

## Steps to Reproduce

```sh
cd concourse
docker-compose up --build
cd testflight
ginkgo -v -untilItFails -focus='runs builds with every version'
```

## Expected Results

The test should succeed reliably.

## Actual Results

I've seen it fail in under 100 runs locally. I also hacked the `AfterEach` to leave the pipeline around rather than destroying it, and when investigating I found some interesting results.

Build 1:

screencapture-localhost-8080-teams-testflight-pipelines-tf-pipeline-1-bc653c72-d5e4-406f-5ea5-b8c82697ca6b-jobs-some-passing-job-builds-1-2018-11-30-14_39_27

Build 2:

screencapture-localhost-8080-teams-testflight-pipelines-tf-pipeline-1-bc653c72-d5e4-406f-5ea5-b8c82697ca6b-jobs-some-passing-job-builds-2-2018-11-30-14_39_40

Build 3:

screencapture-localhost-8080-teams-testflight-pipelines-tf-pipeline-1-bc653c72-d5e4-406f-5ea5-b8c82697ca6b-jobs-some-passing-job-builds-3-2018-11-30-14_39_51

This shows that build 1 ran with `-guid1`, build 2 ran with `-guid2`, but then build 3 ran with...`-guid4`!

**HOWEVER**, if you look at the resource version history, it tells a different story!

screencapture-localhost-8080-teams-testflight-pipelines-tf-pipeline-1-bc653c72-d5e4-406f-5ea5-b8c82697ca6b-resources-some-resource-2018-11-30-14_40_22

This indicates that build 2 actually recorded `-guid3` as its input! This, I think, is where the bug begins; with `-guid3` recorded as an input, it makes sense for the third build to have "skipped" ahead to `-guid4`.

So why was `-guid3` recorded as an input when the build actually ran with `-guid2`?

I dunno. Figure it out!

## Version Info

* Concourse version: `c3896f1ecd34d1b340d876997c4e4c46b75c9c29`
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: local
* Browser (if applicable): n/a
* Did this used to work? not sure, wouldn't be surprised if this has been a bug for a while

### LINKED ISSUE #3240: Remove API dependency on EXEC and Scheduler
## What challenge are you facing?

concourse/rfcs#14

Once #3225 has been merged we can remove the ACTUAL dependency on the exec/scheduler packages. #3225 was just the plumbing work. The real benefit is being able to have our API handlers throw builds into the DB without having to `engineBuild.Resume` or `scheduler.TriggerImmediately`. Then let the `scheduler`/`build starter` take care of actually running them during the next tick.

## What would make this better?

- [x] `buildserver.CreateBuild` should no longer `enginebuild.Resume`. Instead just throw a started build into the db using the plan provided.

- [x] `pipelineserver.CreateBuild` is basically the same as above.

- [x] `jobserver.CreateJobBuild` should no longer `scheduler.TriggerImmediately`

- [x] `buildserver.AbortBuild` should no longer `enginebuild.Abort`. Instead we can just `dbbuild.MarkAsAborted` and a message will be sent to abort the build.

- [x] `jobserver.ListJobInputs` still makes a call to `scheduler.SaveInputMappings`. We should remove this side effect and just let it use whatever exists in `next_build_inputs`.

- [x] Success! The `scheduler.BuildScheduler` interface no longer needs `TriggerImmediately` or `SaveNextInputMapping`. Remove them.

- [x] Also remove the `scheduler`/`exec` dependencies in `atccmd.Command` that get injected into the api handler.

Edit:

- [x] Fix the hardcoded `exec.v2`
- [x] Change `engine_metadata` to `private_plan`?

### LINKED ISSUE #3267: Remove peer url
## What challenge are you facing?

Once #3225 gets merged, we no longer need the `peer url`.

## What would make this better?

 Remove it.

### PR DESCRIPTION
**Pull request by pivotal-jwinters**
This PR is based off #3225 (which fixes #2826)

It also fixes #3240 

...and fixes #3267 

...and fixes #2895

### CODE REVIEW

File: atc/api/buildserver/abort.go [hunk 1]
```diff
@@ -14,14 +13,7 @@ func (s *Server) AbortBuild(build db.Build) http.Handler {
...
 
-		engineBuild, err := s.engine.LookupBuild(aLog, build)
-		if err != nil {
-			aLog.Error("failed-to-lookup-build", err)
-			w.WriteHeader(http.StatusInternalServerError)
-			return
-		}
-
-		err = engineBuild.Abort(aLog)
+		err := build.MarkAsAborted()
```
Comment (vito) [inline atc/api/buildserver/abort.go]: Related: https://github.com/concourse/concourse/issues/1585

Should I prioritize that soon while this is fresh in our heads?

File: atc/api/buildserver/server.go [hunk 2]
```diff
@@ -16,9 +15,7 @@ type Server struct {
 	logger lager.Logger
 
 	externalURL string
-	peerURL     string
 
-	engine              engine.Engine
```
Comment (vito) [inline atc/api/buildserver/server.go]: dope

File: atc/api/jobserver/create_build.go [hunk 3]
```diff
@@ -33,29 +32,10 @@ func (s *Server) CreateJobBuild(pipeline db.Pipeline) http.Handler {
...
-
-		resources, err := pipeline.Resources()
-		if err != nil {
-			logger.Error("failed-to-get-resources", err)
-			w.WriteHeader(http.StatusInternalServerError)
-			return
-		}
-
-		build, _, err := scheduler.TriggerImmediately(logger, job, resources, versionedResourceTypes)
+		build, err := job.CreateBuild()
```
Comment (vito) [inline atc/api/jobserver/create_build.go]: Shouldn't we make sure that this created build is marked 'triggered' so that it gets up-to-date resource versions? As discussed in https://github.com/concourse/concourse/issues/2438

It'd be nice if we kicked the scheduler loop here too. Fast is a feature.

File: atc/api/jobserver/list_inputs.go [hunk 4]
```diff
@@ -28,21 +27,13 @@ func (s *Server) ListJobInputs(pipeline db.Pipeline) http.Handler {
...
-		scheduler := s.schedulerFactory.BuildScheduler(pipeline, s.externalURL, variables)
-
 		resources, err := pipeline.Resources()
 		if err != nil {
 			logger.Error("failed-to-get-resources", err)
 			w.WriteHeader(http.StatusInternalServerError)
 			return
 		}
 
-		err = scheduler.SaveNextInputMapping(logger, job, resources)
```
Comment (vito) [inline atc/api/jobserver/list_inputs.go]: :+1:

File: atc/api/pipelineserver/build.go [hunk 5]
```diff
@@ -22,22 +21,13 @@ func (s *Server) CreateBuild(pipelineDB db.Pipeline) http.Handler {
 			return
 		}
 
-		build, err := pipelineDB.CreateOneOffBuild()
+		build, err := pipeline.CreateStartedBuild(plan)
```
Comment (vito) [inline atc/api/pipelineserver/build.go]: kicking the build tracker here would be nice

File: atc/atccmd/command.go [hunk 6]
```diff
@@ -1029,7 +1005,7 @@ func (cmd *RunCommand) defaultBindIP() net.IP {
 	return net.ParseIP(URL)
 }
 
-func (cmd *RunCommand) defaultURL() flag.URL {
+func (cmd *RunCommand) DefaultURL() flag.URL {
```
Comment (vito) [inline atc/atccmd/command.go]: Should we call this `LocalURL` or something? I always get confused by the name.

File: atc/engine/db_engine.go [hunk 7]
```diff
@@ -15,31 +14,29 @@ import (
 
 const trackLockDuration = time.Minute
 
-func NewDBEngine(engines Engines, peerURL string) Engine {
```
Comment (vito) [inline atc/engine/db_engine.go]: dope

File: atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+	rows, err := tx.Query("SELECT id, private_plan, nonce FROM builds WHERE private_plan IS NOT NULL")
+	if err != nil {
+		return err
+	}
+
+	builds := []build{}
+	for rows.Next() {
+
+		build := build{}
+		if err = rows.Scan(&build.id, &build.plan, &build.nonce); err != nil {
```
[the remark this answers is not in the document]
Comment (vito) [reply atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go]: (Same goes for the 'down' migration.)

File: atc/db/pipeline.go [hunk 9]
```diff
@@ -50,7 +50,10 @@ type Pipeline interface {
 	GetBuildsWithVersionAsInput(int, int) ([]Build, error)
 	GetBuildsWithVersionAsOutput(int, int) ([]Build, error)
 	Builds(page Page) ([]Build, Pagination, error)
+
 	CreateOneOffBuild() (Build, error)
+	CreateStartedBuild(plan atc.Plan) (Build, error)
```
Comment (vito) [inline atc/db/pipeline.go]: Do we still need `CreateOneOffBuild`?

File: atc/db/team.go [hunk 10]
```diff
@@ -43,16 +44,20 @@ type Team interface {
 	OrderPipelines([]string) error
 
 	CreateOneOffBuild() (Build, error)
+	CreateStartedBuild(plan atc.Plan) (Build, error)
```
Comment (vito) [inline atc/db/team.go]: Do we still need `CreateOneOffBuild`?

File: atc/db/pipeline.go [hunk 11]
```diff
@@ -972,6 +975,56 @@ func (p *pipeline) CreateOneOffBuild() (Build, error) {
...
+		"schema":       "exec.v2",
+		"private_plan": encryptedPlan,
+		"public_plan":  plan.Public(),
+		"nonce":        nonce,
+	})
+	if err != nil {
+		return nil, err
+	}
+
+	err = build.saveEvent(tx, event.Status{
```
Comment (vito) [inline atc/db/pipeline.go]: Saving an event here feels a little awkward. When does this normally get sent? Will it be sent twice now?

I wonder if it would be better to create it 'pending' and have the tracker also process pending one-off builds?

File: atc/db/team.go [hunk 12]
```diff
@@ -647,6 +677,55 @@ func (t *team) CreateOneOffBuild() (Build, error) {
...
+		"schema":       "exec.v2",
+		"private_plan": encryptedPlan,
+		"public_plan":  plan.Public(),
+		"nonce":        nonce,
+	})
+	if err != nil {
+		return nil, err
+	}
+
+	err = build.saveEvent(tx, event.Status{
```
Comment (vito) [inline atc/db/team.go]: same concern as above - i'm a little iffy on inserting these in 'started' state

File: atc/api/artifactserver/create.go [hunk 13]
```diff
@@ -0,0 +1,68 @@
...
+		// of 'creating' volume.
+
+		// In the long run CreateVolume should probably return a 'creating'
+		// volume, but there are other changes needed in FindOrCreateContainer
+		// with the way we create volumes for a container
+
+		// I think leaving the race condition is fine for now. Worst case
+		// is a fly execute will fail and the user will need to rerun it.
+
+		artifact, err := volume.InitializeArtifact("", 0)
```
Comment (vito) [inline atc/api/artifactserver/create.go]: 'create' -> 'initialize' -> 'stream in data' feels unintuitive - normally it's 'initialized' only when it has all its data. it seems like this is to paper over the GC race condition. also why are both arguments zero-values?

File: atc/db/worker_artifact.go [hunk 14]
```diff
@@ -0,0 +1,119 @@
...
+	buildID   int
+	createdAt time.Time
+}
+
+func (a *artifact) ID() int              { return a.id }
+func (a *artifact) Name() string         { return a.name }
+func (a *artifact) BuildID() int         { return a.buildID }
+func (a *artifact) CreatedAt() time.Time { return a.createdAt }
+
+func (a *artifact) Volume(teamID int) (CreatedVolume, bool, error) {
```
Comment (vito) [inline atc/db/worker_artifact.go]: surprised this is given a team ID - will it ever have multiple volumes for different teams? or is this just for checking access?

File: atc/exec/task_step.go [hunk 15]
```diff
@@ -440,8 +437,13 @@ func (action *TaskStep) registerOutputs(logger lager.Logger, repository *worker.
 
 		for _, mount := range volumeMounts {
 			if filepath.Clean(mount.MountPath) == filepath.Clean(outputPath) {
-				source := newTaskArtifactSource(mount.Volume)
-				repository.RegisterSource(worker.ArtifactName(outputName), source)
+				source := NewTaskArtifactSource(mount.Volume)
+				repository.RegisterSource(artifact.Name(outputName), source)
+
+				_, err := mount.Volume.InitializeArtifact(outputName, action.buildID)
```
Comment (vito) [inline atc/exec/task_step.go]: So rather than having a step that exists solely to proxy an artifact to the user, we initialize all task outputs as artifacts and just allow them to be downloaded via the API?

Does this mean that each build's task outputs now live for 12 hours? It seems like that could pile up and result in a lot more disk usage if so, assuming a build runs frequently enough.

File: atc/plan.go [hunk 16]
```diff
@@ -28,7 +28,8 @@ type Plan struct {
 type PlanID string
 
 type UserArtifactPlan struct {
-	Name string `json:"name"`
+	ArtifactID int    `json:"artifact_id"`
+	Name       string `json:"name"`
 }
 
 type ArtifactOutputPlan struct {
```
Comment (vito) [inline atc/plan.go]: Should this be removed?

File: atc/scheduler/runner.go [hunk 17]
```diff
@@ -22,15 +22,6 @@ type BuildScheduler interface {
 		resources db.Resources,
 		resourceTypes atc.VersionedResourceTypes,
 	) (map[string]time.Duration, error)
-
-	TriggerImmediately(
```
Comment (vito) [inline atc/scheduler/runner.go]: dope

File: atc/worker_artifact.go [hunk 18]
```diff
@@ -0,0 +1,8 @@
+package atc
+
+type WorkerArtifact struct {
+	ID        int    `json:"id"`
+	Name      string `json:"name"`
+	BuildID   int    `json:"build_id"`
+	CreatedAt int64  `json:"created_at"`
```
Comment (vito) [inline atc/worker_artifact.go]: Not actually sure what format we typically use for timestamps in the API, but we should check this to make sure we're consistent.

File: fly/commands/internal/executehelpers/inputs.go [hunk 19]
```diff
@@ -127,18 +131,30 @@ func TaskInputsContainsName(inputs []atc.TaskInputConfig, name string) bool {
...
+	fact atc.PlanFactory,
+	team concourse.Team,
+	inputMappings []flaghelpers.InputPairFlag,
+	includeIgnored bool,
+) (map[string]Input, error) {
+
 	kvMap := map[string]Input{}
 
 	for _, i := range inputMappings {
+		artifact, err := Upload(team, i.Path, includeIgnored)
```
Comment (vito) [inline fly/commands/internal/executehelpers/inputs.go]: I noticed we don't show upload/download progress anymore, now that the steps don't print it. It'd be nice to have that back.

File: atc/api/buildserver/create.go [hunk 20]
```diff
@@ -22,22 +22,13 @@ func (s *Server) CreateBuild(team db.Team) http.Handler {
...
 		}
 
-		engineBuild, err := s.engine.CreateBuild(hLog, build, plan)
-		if err != nil {
-			hLog.Error("failed-to-start-build", err)
-			w.WriteHeader(http.StatusInternalServerError)
-			return
-		}
-
-		go engineBuild.Resume(hLog)
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/buildserver/create.go]: yeah can we add this to a general LISTEN/NOTIFY story? I think we could take this approach in a few more places.

File: atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go]: heh, yeah that makes sense. I'll batch it.

File: atc/api/accessor/accessor_test.go [hunk 21]
```diff
@@ -651,12 +650,16 @@ var _ = Describe("Accessor", func() {
...
-		Entry("owner :: "+atc.SendInputToBuildPlan, atc.SendInputToBuildPlan, "owner", true),
-		Entry("member :: "+atc.SendInputToBuildPlan, atc.SendInputToBuildPlan, "member", true),
-		Entry("viewer :: "+atc.SendInputToBuildPlan, atc.SendInputToBuildPlan, "viewer", false),
+		Entry("owner :: "+atc.CreateArtifact, atc.CreateArtifact, "owner", true),
+		Entry("member :: "+atc.CreateArtifact, atc.CreateArtifact, "member", true),
+		Entry("viewer :: "+atc.CreateArtifact, atc.CreateArtifact, "viewer", false),
+
+		Entry("owner :: "+atc.GetArtifact, atc.GetArtifact, "owner", true),
+		Entry("member :: "+atc.GetArtifact, atc.GetArtifact, "member", true),
+		Entry("viewer :: "+atc.GetArtifact, atc.GetArtifact, "viewer", true),
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/accessor/accessor_test.go]: hmm yeah maybe we should make it member only, there could be sensitive info in these artifacts.

File: atc/api/artifactserver/create.go [hunk 22]
```diff
@@ -0,0 +1,68 @@
...
+
+		// This happens because CreateVolume returns a 'created' instead
+		// of 'creating' volume.
+
+		// In the long run CreateVolume should probably return a 'creating'
+		// volume, but there are other changes needed in FindOrCreateContainer
+		// with the way we create volumes for a container
+
+		// I think leaving the race condition is fine for now. Worst case
+		// is a fly execute will fail and the user will need to rerun it.
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/artifactserver/create.go]: It gets GC'ed because it returns a created volume, with nothing keeping it around. I'll investigate to see if I can do some refactoring to get it to return a creating volume.

File: atc/api/artifactserver/create.go [hunk 23]
```diff
@@ -0,0 +1,68 @@
...
+
+		artifact, err := volume.InitializeArtifact("", 0)
+		if err != nil {
+			hLog.Error("failed-to-initialize-artifact", err)
+			w.WriteHeader(http.StatusInternalServerError)
+			return
+		}
+
+		err = volume.StreamIn("/", r.Body)
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/artifactserver/create.go]: yep

File: atc/api/artifactserver/create.go [hunk 24]
```diff
@@ -0,0 +1,68 @@
...
+	"github.com/concourse/concourse/atc/worker"
+)
+
+func (s *Server) CreateArtifact(team db.Team) http.Handler {
+	hLog := s.logger.Session("create-artifact")
+
+	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		w.Header().Set("Content-Type", "application/json")
+
+		// TODO: can probably check if fly sent us an etag header
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/artifactserver/create.go]: yep

File: atc/api/buildserver/server.go (hunk 2 above)
Comment (pivotal-jwinters) [reply atc/api/buildserver/server.go]: yep

File: atc/api/buildserver/abort.go (hunk 1 above)
Comment (pivotal-jwinters) [reply atc/api/buildserver/abort.go]: Maybe this could be something to look into when we do the broader LISTEN/NOTIFY work?

File: atc/api/artifactserver/get.go [hunk 25]
```diff
@@ -0,0 +1,66 @@
...
+			w.WriteHeader(http.StatusInternalServerError)
+			return
+		}
+
+		defer reader.Close()
+
+		_, err = io.Copy(w, reader)
+		if err != nil {
+			logger.Error("failed-to-encode-artifact", err)
+			w.WriteHeader(http.StatusInternalServerError)
```
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/api/artifactserver/get.go]: not sure what you mean? why does this write multiple headers?

File: atc/api/jobserver/create_build.go (hunk 3 above)
Comment (pivotal-jwinters) [reply atc/api/jobserver/create_build.go]: This already happens here: https://github.com/concourse/concourse/blob/ca9fd7c33fe63291ef291d40c4bd9ccc2ba692d4/atc/db/pipeline.go#L254-L255

File: atc/api/jobserver/list_inputs.go (hunk 4 above)
Comment (pivotal-jwinters) [reply atc/api/jobserver/list_inputs.go]: yep

File: atc/api/pipelineserver/build.go (hunk 5 above)
Comment (pivotal-jwinters) [reply atc/api/pipelineserver/build.go]: LISTEN/NOTIFY work?

File: atc/atccmd/command.go (hunk 6 above)
Comment (pivotal-jwinters) [reply atc/atccmd/command.go]: ¯\_(ツ)_/¯

File: atc/engine/db_engine.go (hunk 7 above)
Comment (pivotal-jwinters) [reply atc/engine/db_engine.go]: yep

File: atc/db/pipeline.go (hunk 9 above)
Comment (pivotal-jwinters) [reply atc/db/pipeline.go]: ugh, yes. its used absolutely everywhere in the tests and I did not want to mess with that.

File: atc/db/team.go (hunk 10 above)
Comment (pivotal-jwinters) [reply atc/db/team.go]: so. many. tests.

File: atc/db/pipeline.go (hunk 11 above)
Comment (pivotal-jwinters) [reply atc/db/pipeline.go]: I agree, but i think this is a larger discussion around build state. Seems like we need an intermediate `planned` state.

This means the `BuildStarter` actually becomes a `BuildPlanner`.

File: atc/db/team.go (hunk 12 above)
Comment (pivotal-jwinters) [reply atc/db/team.go]: RIP BuildStarter, long live BuildPlanner

File: atc/db/worker_artifact.go (hunk 14 above)
Comment (pivotal-jwinters) [reply atc/db/worker_artifact.go]: yeah its just for checking access. its really unfortunate that teamID exists on the volume itself. It would be a lot nicer and more intuitive if each "higher level resource" had the teamID.

File: atc/exec/task_step.go (hunk 15 above)
Comment (pivotal-jwinters) [reply atc/exec/task_step.go]: TBH I never even considered putting this in its own step (which is hilarious because I had to delete the old output artifact build step to make this change).

It wouldn't really help us with the lifecycle, but it would at least limit the number of `artifacts` that get created to only one-off builds.

File: atc/plan.go (hunk 16 above)
Comment (pivotal-jwinters) [reply atc/plan.go]: nah, we still need it

File: atc/scheduler/runner.go (hunk 17 above)
Comment (pivotal-jwinters) [reply atc/scheduler/runner.go]: yep

File: atc/worker_artifact.go (hunk 18 above)
Comment (pivotal-jwinters) [reply atc/worker_artifact.go]: from what i saw we aren't consistent lol

File: fly/commands/internal/executehelpers/inputs.go (hunk 19 above)
Comment (pivotal-jwinters) [reply fly/commands/internal/executehelpers/inputs.go]: erm yeah, i'll look into that

File: atc/api/artifactserver/create.go (hunk 13 above)
Comment (pivotal-jwinters) [reply atc/api/artifactserver/create.go]: yes yes and yes. we can have this flow make more sense if we figure out the race condition.

lets just pretend those zero values aren't there... they get used for artifacts from build outputs.

**Comment by pivotal-jwinters** [comment]
- [ ] batch migration
- [ ] get artifact -> member only
- [ ] creating volume
- [ ] upload/download status
- [ ] artifact lifecycle

File: fly/commands/internal/executehelpers/inputs.go (hunk 19 above)
Comment (pivotal-jwinters) [reply fly/commands/internal/executehelpers/inputs.go]: I spoke with @xtremerui and he seems to think this got removed a while ago. If we want that back can we create a separate issue?

Comment (vito) [reply fly/commands/internal/executehelpers/inputs.go]: It's there for me:

```
~/w/concourse (fix-dashboard-search) $ fly -t ci e -c ci/tasks/docker-compose-watsjs.yml -i concourse=. -p
executing build 4989469 at https://ci.concourse-ci.org/builds/4989469 
initializing
concourse: 16.54 MiB/s 0s                                                       
running concourse/ci/tasks/scripts/with-docker-compose concourse/ci/tasks/scripts/watsjs
/tmp/build/e55deab7/concourse /tmp/build/e55deab7
Creating network "concourse_default" with the default driver
Pulling db (postgres:)...
```

It's not a progress bar, but it still shows the upload rate and duration.

It shouldn't take long to restore it, and I'd like to avoid user-facing regressions on `master` that prevent us from shipping, so I don't want to merge without it. 😅 

You could probably just hoist the code from the user artifact step into `fly`:

https://github.com/concourse/concourse/blob/b20ee6770be162614a2d7e561c5bff095b81db93/atc/exec/user_artifact_step.go#L54-L62

File: atc/exec/task_step.go (hunk 15 above)
Comment (vito) [reply atc/exec/task_step.go]: Hmm should we bring the artifact output step back, then? I wouldn't want to ship with all task outputs lasting for 12 hours.

File: atc/api/artifactserver/create.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (vito) [reply atc/api/artifactserver/create.go]: Sounds fine.

File: atc/exec/task_step.go (hunk 15 above)
Comment (pivotal-jwinters) [reply atc/exec/task_step.go]: Yeah working on that now. It adds a lot better symmetry :)

File: fly/commands/internal/executehelpers/inputs.go (hunk 19 above)
Comment (pivotal-jwinters) [reply fly/commands/internal/executehelpers/inputs.go]: ah cool! im going to pull this into fly execute instead of having it in the step.

File: atc/plan.go (hunk 16 above)
Comment (pivotal-jwinters) [reply atc/plan.go]: err I originally thought you we're talking about the `UserArtifactPlan` because of how its highlighted. I now realize you actually meant the ArtifactOutputPlan, which coincidently we are bringing back because of other things you mentioned :)

Comment (pivotal-jwinters) [reply atc/plan.go]: glad it never got removed in the first place ;)

File: atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go]: I actually remember this now. I don't think this needs to be batched. The `private_plan` only exists for the duration that the build is running. We query for builds where `private_plan` IS NOT NULL so that shouldn't actually be very many things.

**Comment by pivotal-jwinters** [comment]
@vito based on these commits I just pushed, and some comments, I think I addressed all your concerns. Let me know if you think there's something that I missed.

**Comment by pivotal-jwinters** [comment]
Also fixed the double status. NOW it should be good to go.

File: atc/plan.go (hunk 16 above)
Comment (vito) [reply atc/plan.go]: lol, yep 👍

File: atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (pivotal-jwinters) [reply atc/db/migration/migrations/1551384520_fix_build_private_plan.up.go]: Currently there are only 42 builds on wings where this is true.

File: atc/api/buildserver/create.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (vito) [reply atc/api/buildserver/create.go]: created https://github.com/concourse/concourse/issues/3508
