### PR TITLE
fixed a bug of error invalidated-worker-resource-cache-exists

### LINKED ISSUE #8413: Upgrading to 7.8.0 introduced `invalidated-worker-resource-cache-exists` in some of our workers
## Summary

We recently upgraded from 7.7.1 to 7.8.0 and it appeared to go fine, however pretty soon teams started complaining that their resource GETs were failing due to "invalidated-worker-resource-cache-exists", restarting the underlying node and clearing the resource cache did nothing, however restarting the pod (with no ephemeral storage) worked for a short time.
We can not reproduce this in our dev environment either, it only affects some teams too, not all of them.

## Steps to reproduce

Once upgraded, each team has it's own worker pod on it's own worker node with ephemeral storage as an EBS volume for duration of the underlying node. When left as is, some teams reported seeing "invalidated-worker-resource-cache-exists" - nothing changed after upgrade.

## Expected results

Before upgrade to 7.8.0, these issues were not happening - resource caches appeared to work fine

## Actual results

"invalidated-worker-resource-cache-exists" printed for several teams on resource "GET" step

## Additional context

From looking at the [code](https://github.com/concourse/concourse/blob/v7.8.0/atc/db/worker_resource_cache.go#L40), it appears as though:
```
// If the found worker resource cache's worker base resource type id is
// 0, then means the original source has been invalidated. But as this
// worker resource cache can still be found and used, so before this cache
// is GC-ed, let's not recreate the cache.
if uwrc.WorkerBaseResourceTypeID == 0 {
	return nil, false, errors.New("invalidated-worker-resource-cache-exists")
}
```
is the cause. Getting teams to flush their caches independently did not work.
We have upgraded the underlying EC2 instance for the database as it was looking a bit overutilised but this issue still occurred.

I have looked at the breaking Vault change as we did use that and although it sounded similar, I believe they use separate caches and we haven't got the creds cache enabled - so I think it is separate.

## Triaging info

* Concourse version: 7.8.0
* Browser (if applicable):
* Did this used to work? yes

### PR DESCRIPTION
**Pull request by evanchaoli**
## Changes proposed by this PR

closes #8413

* [x] done

## Release Note

Fixed a bug of error "invalidated-worker-resource-cache-exists".

### CODE REVIEW

File: atc/db/volume_test.go [hunk 1]
```diff
@@ -374,17 +369,76 @@ var _ = Describe("Volume", func() {
...
+			It("initializing resource cache on the new volume should not fail", func() {
+				err := newVolume.InitializeResourceCache(resourceCache)
+				Expect(err).ToNot(HaveOccurred())
+			})
+
+			It("leaves the volume owned by the container", func() {
+				Expect(newVolume.Type()).To(Equal(db.VolumeTypeContainer))
+			})
+
+			It("original invalidated resource cache volume still be found", func() {
```
Comment (xtremerui) [inline atc/db/volume_test.go:435]: Isn't this one the repeat of line line 418 - 421?

maybe you want to remove those in the before block?
```suggestion
			It("resource cache volume still be found on worker 1 after original invalidated on worker 0", func() {
```

**Review by xtremerui — APPROVED** [review]
LGTM
