### PR TITLE
Optimize limit active tasks strategy logic

### LINKED ISSUE #7791: `limit-active-tasks` causing high database CPU and eventual deadlock
## Summary

We have been investigating elastic scaling of our workers as our workload can cause large spikes in the number of jobs/tasks (~1000). During these investigation we have found situations where;

- the workers CPUs has dropped to effectively 0%
- `steps_waiting` > 500
- `worker_tasks` unrealistic/unaccountable
- `steps_waiting_duration` linearly increasing
- no tasks are scheduled and manual intervention is required

In these situations, cancelling pipelines or jobs eventually brings things back into life. Upon investigation we have seen high database CPU with the majority of queries:

```sql
UPDATE workers SET active_tasks = active_tasks+? WHERE name = $1 RETURNING "active_tasks"
```

And the corresponding `active_tasks-?`

image
image

## Steps to reproduce

Ensure `CONCOURSE_CONTAINER_PLACEMENT_STRATEGY` includes `limit-active-tasks`

<details>
  <summary>pipeline.yml</summary>
  
```yml
resources:
  - name: busybox
    type: registry-image
    source:
      repository:busybox
jobs:
  - name: wait
    plan:
      - get: busybox
      - in_parallel:
        - task: "task-1"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-2"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-3"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-4"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-5"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-6"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-7"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-8"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-9"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-10"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-11"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-12"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-13"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-14"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-15"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-16"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-17"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-18"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-19"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-20"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-21"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-22"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-23"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-24"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-25"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-26"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-27"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-28"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-29"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-30"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-31"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-32"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-33"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-34"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-35"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-36"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-37"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-38"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-39"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-40"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-41"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-42"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-43"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-44"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-45"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-46"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-47"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-48"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-49"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-50"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-51"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-52"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-53"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-54"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-55"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-56"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-57"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-58"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-59"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-60"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-61"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-62"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-63"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-64"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-65"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-66"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-67"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-68"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-69"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-70"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-71"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-72"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-73"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-74"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-75"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-76"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-77"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-78"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-79"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-80"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-81"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-82"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-83"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-84"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-85"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-86"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-87"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-88"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-89"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-90"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-91"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-92"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-93"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-94"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-95"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-96"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-97"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-98"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-99"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-100"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-101"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-102"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-103"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-104"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-105"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-106"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-107"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-108"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-109"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-110"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-111"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-112"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-113"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-114"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-115"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-116"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-117"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-118"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-119"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-120"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-121"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-122"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-123"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-124"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-125"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-126"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-127"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-128"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-129"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-130"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-131"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-132"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-133"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-134"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-135"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-136"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-137"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-138"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-139"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-140"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-141"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-142"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-143"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-144"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-145"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-146"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-147"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-148"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-149"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-150"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-151"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-152"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-153"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-154"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-155"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-156"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-157"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-158"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-159"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-160"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-161"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-162"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-163"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-164"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-165"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-166"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-167"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-168"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-169"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-170"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-171"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-172"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-173"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-174"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-175"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-176"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-177"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-178"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-179"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-180"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-181"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-182"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-183"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-184"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-185"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-186"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-187"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-188"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-189"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-190"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-191"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-192"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-193"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-194"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-195"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-196"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-197"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-198"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-199"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
        - task: "task-200"
          image: busybox
          config:
            platform: linux
            run:
              path: sh
              args:
                [
                  "-c",
                  "for i in $(seq 10000); do echo hello_world | sha512sum > /dev/null; echo -ne \"\\r$i\"; done;",
                ]
```
</details>

In our test environment, we can start a number of concurrent jobs using the above pipeline - however - any pipeline with a high number of jobs and that takes some time to complete should work. We slowly start more and more builds, until eventually the number of waiting tasks causes a "dead lock"

Our test environment manages many, many more waiting steps before being "locked" than our production environment. We are not currently certain why this is the case.

## Expected results

Tasked are queued and the number of waiting tasks doesn't effect the performance of the cluster.

## Actual results

Eventual deadlock. No more tasks are scheduled and the workers are doing nothing.

## Additional context

Related issues (?): 
- https://github.com/concourse/concourse/issues/3695
- https://github.com/concourse/concourse/issues/7085

Related code:
https://github.com/concourse/concourse/blob/master/atc/worker/placement.go#L283-L303
```go
func (strategy limitActiveTasksStrategy) Approve(logger lager.Logger, worker db.Worker, spec runtime.ContainerSpec) error {
	if spec.Type != db.ContainerTypeTask {
		return nil
	}

	activeTasks, err := worker.IncreaseActiveTasks()
	if err != nil {
		return err
	}

	if strategy.MaxTasks > 0 && activeTasks > strategy.MaxTasks {
		_, err := worker.DecreaseActiveTasks()
		if err != nil {
			logger.Error("failed-to-decrease-active-tasks", err)
		}

		return ErrTooManyActiveTasks
	}

	return nil
}
```

## Triaging info

- Concourse version: 7.6.0
- \# web instances: 6 (2 CPU/ 4GB RAM in AWS ECS Fargate)
- \# worker instances: 1-10 (AWS EC2 m5.4xlarge)
- Database: PostgreSQL 11.1 db.m5.2xlarge

### PR DESCRIPTION
**Pull request by xtremerui**
## Changes proposed by this PR

 * return early to avoid unnecessary query
 * use get instead of update to reduce DB lock on rows
 * only increase the count in the end

It should help reducing the DB load and the chance of dead lock, especially under heavy load.

closes #7791 

## Release Note

* Optimize limit-active-tasks strategy to reduce DB load and avoid deadlocking when under heavy load.

### CODE REVIEW

File: atc/worker/placement.go [hunk 1]
```diff
@@ -281,25 +281,22 @@ func (strategy limitActiveTasksStrategy) Order(logger lager.Logger, pool Pool, w
 }
 
 func (strategy limitActiveTasksStrategy) Approve(logger lager.Logger, worker db.Worker, spec runtime.ContainerSpec) error {
-	if spec.Type != db.ContainerTypeTask {
+	if spec.Type != db.ContainerTypeTask || strategy.MaxTasks == 0 {
 		return nil
 	}
 
-	activeTasks, err := worker.IncreaseActiveTasks()
+	activeTasks, err := worker.ActiveTasks()
```
Comment (clarafu) [inline atc/worker/placement.go:288]: Can there be the case when there are multiple threads fetch the active tasks at the same time and then both increase active tasks even though it goes past the maximum? For example, max tasks = 1 and there are two threads, both fetch that active tasks are 0 (because they run at the exact same time) and then both increase active tasks so then active tasks = 2.

Comment (xtremerui) [reply atc/worker/placement.go:288]: IMHO the potential race of increasing active tasks is trivial as long as the next task cant be scheduled to this particular worker.

From the original issue, it is more concern on the mismatch between task container counts and active tasks count in the row, which should not be affected by the race here.

Comment (clarafu) [reply atc/worker/placement.go:288]: But that would mean when the user sets a max tasks of 1, theres the possibility of it getting to 2,3, or more? I think that might be a problem because then the user will be expecting us to cap the mask tasks at 1 but then in reality there are more than 1 task running.

I guess I'm still uncertain as to where the bug in this original code is that will cause the mismatch between task container counts and active tasks counts. 🤔  Which is why I'm not sure if this will solve the problem? Do you have a theory as to why this code can result in a mismatch of counts?

To be clear, I think there is definitely something that needs to be done to fix this problem. Like maybe we can do a `SELECT FOR UPDATE` in order to lock the `active_tasks` row so that it cannot be updated while it is being selected by one thread within the same transaction? But I also don't know if we should do that because doing `FOR UPDATE` locks have not worked out well for us in the past haha. Whenever I search online, people always say to do a straight update is actually the easiest rather than doing a select and then update. Maybe we could have the update only work if it's count is less than the max tasks? Like
```
UPDATE workers SET active_tasks=active_tasks+1 WHERE name = (worker-name) AND active_tasks < (max-tasks-num) RETURNING active_tasks;`
```
And then we can check if the returned `active_tasks` is nil or not. If it is nil that means it did not update, meaning that it is has hit the max active tasks and we can return the ErrTooManyActiveTasks error.

Comment (xtremerui) [reply atc/worker/placement.go]: OK I have updated the method

**Review by clarafu — APPROVED** [review]
It looks good to me!! 👍
