### PR TITLE
atc/exec: don't panic on RetryStep

### LINKED ISSUE #5077: Continual web panic until workers are redeployed
This issue happens rarely, maybe once a month, but the biggest problem is that after it starts it keeps happening across all the web nodes until we resort to redeploying all the workers.

```
panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb4a25a]goroutine 175554 [running]:github.com/concourse/concourse/atc/exec.(*RetryStep).Succeeded(0xc066d64690, 0x2)
/tmp/build/1c3187db/concourse/atc/exec/retry_step.go:47 +0x2agithub.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841da0, 0xc066d64690, 0x284a7e0, 0xc0680fe400, 0x424101)
/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x31github.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841e20, 0xc066d647b0, 0x284a7e0, 0xc0680fe4c0, 0xc05ec4cc90)
/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x5cgithub.com/concourse/concourse/atc/exec.OnFailureStep.Succeeded(...)
/tmp/build/1c3187db/concourse/atc/exec/on_failure.go:44github.com/concourse/concourse/atc/exec.EnsureStep.Succeeded(0x284a7a0, 0xc0680fe640, 0x2841da0, 0xc066d64870, 0xc051486660)
/tmp/build/1c3187db/concourse/atc/exec/ensure_step.go:58 +0x31github.com/concourse/concourse/atc/engine.(*engineBuild).Run(0xc03c79bd60, 0x2895fa0, 0xc00578d020)
/tmp/build/1c3187db/concourse/atc/engine/engine.go:215 +0x8cdcreated by github.com/concourse/concourse/atc/builds.(*Tracker).Track
/tmp/build/1c3187db/concourse/atc/builds/tracker.go:49 +0x425
```

There was a similar issue - https://github.com/concourse/concourse/issues/3989 - so perhaps it was only partially fixed.

## Version Info

* Concourse version: 5.7.0

### PR DESCRIPTION
**Pull request by YoussB**
## What does this PR accomplish?

**Bug Fix** | Feature | Documentation

closes #5077  .

## Changes proposed by this PR:

* Step validation now disallows `attempts: 0`
* Don't panic if `RetryStep` doesn't have a `LastAttempt`

## Notes to reviewer:

Prior to this fix, the panic is easy to reproduce - just set a pipeline with some step that has `attempts: 0`.

We don't have a reproducible where `RetryStep` panics even with `attempts > 0`, but this should fix that issue as well.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [x] Updated [Release notes]

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

File: atc/exec/retry_step.go [hunk 1]
```diff
@@ -44,5 +44,8 @@ func (step *RetryStep) Run(ctx context.Context, state RunState) error {
 
 // Succeeded delegates to the last step that it ran.
 func (step *RetryStep) Succeeded() bool {
+	if step.LastAttempt == nil {
```
Comment (xtreme-sameer-vohra) [inline atc/exec/retry_step.go:47]: This makes sense and is defensive.
One concern is that since we don't have a way of reproducing this with attempts > 0, this masks a situation where `Succeeded` is being invoked before/concurrently with `Run`, which might be undefined behaviour.

File: atc/exec/retry_step_test.go [hunk 2]
```diff
@@ -339,4 +339,16 @@ var _ = Describe("Retry Step", func() {
...
+		BeforeEach(func() {
+			step = Retry()
+		})
+
+		Describe("Succeeded", func() {
+			It("should return false", func() {
+				Expect(step.Succeeded()).To(BeFalse())
+			})
+		})
+	})
```
Comment (xtreme-sameer-vohra) [inline atc/exec/retry_step_test.go:353]: Could we add another similar case or replace this case, where if `Retry.Succeeded` is invoked with attempts>0, but without first invoking `Run`, it should also return false ?

Comment (YoussB) [reply atc/exec/retry_step_test.go]: thanks, we added this test.

File: atc/exec/retry_step.go (hunk 1 above)
Comment (YoussB) [reply atc/exec/retry_step.go:47]: I agree, but I am not sure how to avoid this situation. Also, @aoldershaw and I were unable to find a specific case where this happens except if the attempts was set to `0`. so this is to further safeguard against incorrect invocations.

**Comment by YoussB** [comment]
Thanks @xtreme-sameer-vohra. 
@xtremerui and I have addressed your comments.

File: atc/exec/retry_step.go (hunk 1 above)
Comment (YoussB) [reply atc/exec/retry_step.go:47]: also, #5842 should help further safeguard against possible panics like this one.

**Comment by YoussB** [comment]
@xtreme-sameer-vohra I rebased the release notes, although I think it will be nice if this makes it to v6.4.0, if it is complete.

**Comment by xtreme-sameer-vohra** [comment]
lgtm !! updated the release notes to fix the conflict
