### PR TITLE
web: add red border to failing steps

### LINKED ISSUE #4111: Make auto-collapsed failed steps easier to notice
Follow-up to #4058 / #4051 - failed steps no longer auto-expand, which is nice because it keeps them from shoving other failed steps offscreen, but I find it hard to notice *which* step failed.

For example:

image

That little ❌ is a bit hard to notice, mainly because I tend to look at the left side of the screen I guess, and it's pretty far from the step name making it hard to scan over and see what step it is.

Maybe we could make the whole header background for the step red? 😮 

/cc @pivotal-jamie-klassen @Lindsayauchin

### PR DESCRIPTION
**Pull request by jomsie**
fixes #4111

# Release Note
```tex
\note{feature}{
  We noticed after \link{PR #4058}{https://github.com/concourse/concourse/pull/4058} 
  (where build steps are collapsed by default) that it wasn't very easy to see failing steps.
  
  Now a failed step has a simple red border around its header and an erroring step has an
  orange border
  \link{#4164}{https://github.com/concourse/concourse/pull/4164} 
}
```

### CODE REVIEW

File: web/elm/src/Build/Styles.elm [hunk 1]
```diff
@@ -141,10 +142,16 @@ triggerTooltip =
...
+stepHeader : StepState -> List (Html.Attribute msg)
+stepHeader state =
     [ style "display" "flex"
     , style "justify-content" "space-between"
+    , case state of
+        StepStateFailed ->
+            style "border" "1px solid #C24433"
+
+        _ ->
+            style "border" "none"
```
Comment (vito) [inline web/elm/src/Build/Styles.elm]: `none` vs. `1px` will result in content slightly jumping when the border is added - similar to https://github.com/concourse/concourse/issues/3078

Comment (jomsie) [reply web/elm/src/Build/Styles.elm]: Good snag! Will fix!

File: web/elm/src/Build/Styles.elm [hunk 2]
```diff
@@ -141,10 +142,19 @@ triggerTooltip =
...
+stepHeader state =
     [ style "display" "flex"
     , style "justify-content" "space-between"
+    , style "border" <|
+        "1px solid "
+            ++ (case state of
+                    StepStateFailed ->
+                        Colors.failure
+
+                    _ ->
```
Comment (vito) [inline web/elm/src/Build/Styles.elm]: :ghost: Scope creeping, but can we do the same for errored steps? Those are in the same boat: they cause a build failure (well, error) but are hard to notice when auto-collapsed.

I don't think there are any other states we care about. :thinking:

Comment (pivotal-jamie-klassen) [reply web/elm/src/Build/Styles.elm]: Here's a prototype, but let's get @Lindsayauchin in on this sooner rather than later.
Screen Shot 2019-07-31 at 3 21 45 PM

**Comment by jomsie** [comment]
[wats test failing](https://ci.concourse-ci.org/builds/6627310#L5d41da29:721), running locally it passes when it doesn't timeout

File: web/elm/src/Build/Styles.elm (hunk 2 above)
Comment (Lindsayauchin) [reply web/elm/src/Build/Styles.elm]: @vito @pivotal-jamie-klassen Makes sense. I like it!

Comment (vito) [reply web/elm/src/Build/Styles.elm]: @Lindsayauchin @pivotal-jamie-klassen More :ghost: scope creep: what do you think of adding a yellow border for running steps, since they're auto-collapsed too?

some context: https://github.com/concourse/concourse/issues/2608#issuecomment-517296718

**Comment by cirocosta** [comment]
hey, I just wanted to say that this is amazing ❤️ ! thank you all! (@xtremerui shares the same thought!)
