### PR TITLE
web: fix styles on groups bar

### LINKED ISSUE #3561: [ui] pipeline groups overlap if the browser windows isn't wide enough
## Bug Report

If a pipeline has many groups and the browser window is narrow enough to force wraparound, the second row of groups overlaps the first.

## Steps to Reproduce

1) Create a pipeline with many groups
2) Make the browser window narrow

## Expected Results

2 neat non-overlapping rows of groups

## Actual Results

rows overlap, reducing legibility

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
fixes #3561

### CODE REVIEW

File: web/elm/src/Pipeline/Styles.elm [hunk 1]
```diff
@@ -23,16 +22,9 @@ groupsBar : List (Html.Attribute msg)
 groupsBar =
     [ style "background-color" Colors.groupsBarBackground
```
Comment (xtreme-james-cooper) [inline web/elm/src/Pipeline/Styles.elm]: Erm... why is this a block of styles and not a List of string string pairs? o.O

Comment (pivotal-jamie-klassen) [reply web/elm/src/Pipeline/Styles.elm]: [elm 0.19](https://discourse.elm-lang.org/t/style-from-v0-18-to-v0-19/1766)
