### PR TITLE
topgun/k8s: ensure garden configuration can be properly set for the worker pods

### LINKED ISSUE #3237: topgun/k8s: garden properties configuration
## What challenge are you facing?

With the move towards passing [`gdn`](https://github.com/cloudfoundry/guardian/blob/c854b9f04c9424dd9282458fd1c08a015f3b3899/cmd/gdn/main.go)-specific [configuration](https://github.com/cloudfoundry/guardian/blob/c854b9f04c9424dd9282458fd1c08a015f3b3899/guardiancmd/command.go#L60-L68) either through environment variables or using a config file, we end up removing all of those `CONCOURSE_GARDEN_` variables from `values.yaml` in the Helm chart (https://github.com/cirocosta/charts/tree/concourse/5.x-release-2), leaving the configuration to be done through additional mounts with ConfigMaps or additional environment variables.

## What would make this better?

To make sure we have that really working, i.e., the configuration being properly used by `gdn`, we could have a test that:

- includes a config file through a [ConfigMap](https://cloud.google.com/kubernetes-engine/docs/concepts/configmap); then
  - verify that `gdn` uses it.
- make use of [`env`](https://github.com/helm/charts/blob/4fcb0b0d338e923f31d2be4c44db0f533aef7d9f/stable/concourse/values.yaml#L1297-L1300) specifying extra `CONCOURSE_GARDEN_` vars; then
  - verify that `gdn` uses it.

Example use case: configuring the network range for the containers (https://github.com/concourse/concourse/issues/847#issuecomment-461345629)

### LINKED ISSUE #3405: Invalid use of gdn's flag for supplying config files
## Bug Report

When trying to spin up a Concourse worker using a `.ini` file for the `gdn`, `worker_linux.go` is using a single dash (`-`) for passing the path to the configuration file:

https://github.com/concourse/concourse/blob/e19711506043a1af0ad273e76c2ece8d97c72ae9/cmd/concourse/worker_linux.go#L101

Which is not what `gdn` expects (see our use of other flags):

https://github.com/concourse/concourse/blob/e19711506043a1af0ad273e76c2ece8d97c72ae9/cmd/concourse/worker_linux.go#L105-L115

## Steps to Reproduce

0. create a `garden-config.ini` file:

```
[server]
  something-totally-wrong = 1337
```

1. have `concourse/concourse` in the SHA as of this writing (e19711506043a1af0ad273e76c2ece8d97c72ae9);

2. modify `docker-compose.yml` to include a volume that mounts a local `garden.ini` configuration file to a path within the worker container and point to it through the `CONCOURSE_GARDEN_CONFIG_FILE` environment variables

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 38ddeb13f..4c97360e3 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -37,12 +37,15 @@ services:
       dockerfile: ${DOCKERFILE}
     image: concourse/concourse:local
-    command: worker
+    command: [ worker, --garden-config=/garden-config.ini ]
+    volumes: [ './garden-config.ini:/garden-config.ini:ro' ]
     privileged: true
     depends_on: [web]
     ports:
     - 7777:7777
     - 7788:7788
     environment:
       CONCOURSE_LOG_LEVEL: debug
       CONCOURSE_TSA_HOST: web:2222
       CONCOURSE_EPHEMERAL: ${CONCOURSE_EPHEMERAL:-true}
```

## Expected Results

Fail in a way that is "good" (reads the file we set as the configuration).

## Actual Results

```
unknown flag `c'
unknown flag `c'
```

## Version Info

* Concourse version: e19711506043a1af0ad273e76c2ece8d97c72ae9
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

### PR DESCRIPTION
**Pull request by cirocosta**
This ensures that our 5.x branch can have garden properties passed not only through environment variables as usual, but also ConfigMaps, which can be referenced through `CONCOURSE_GARDEN_CONFIG`.

fixes #3237
fixes #3405

### CODE REVIEW

File: cmd/concourse/worker_linux.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ func (cmd *WorkerCommand) gdnRunner(logger lager.Logger) (ifrit.Runner, error) {
 	gdnFlags := []string{}
 
 	if cmd.Garden.GardenConfig.Path() != "" {
-		gdnFlags = append(gdnFlags, "-config", cmd.Garden.GardenConfig.Path())
+		gdnFlags = append(gdnFlags, "--config", cmd.Garden.GardenConfig.Path())
```
Comment (cirocosta) [inline cmd/concourse/worker_linux.go]: see https://github.com/concourse/concourse/issues/3406
