### PR TITLE
Skip over containers on stalled workers when deleting missing

### LINKED ISSUE #4536: Stalled workers' containers get cleaned up from ATC DB
## Bug Report

When a worker enters stalled state but has containers that were reported missing to the ATC, ATC will continue to count down the grace period and delete that container record after 5 minutes default (plus or minus 30 seconds for the GC tick). This leads to a state where a container still exists on the worker when it comes back online, but no record of the container exists on ATC anymore. ATC can continue sending traffic to that worker without knowledge of this state, and while Garden will reject additional container creation requests beyond the default limit of 250, it would be better if container capacity was synced up between the worker and ATC.

## Steps to Reproduce
1. modify a container row and insert a time value into the missing_since column.
2. turn off eth0 on the worker so this simulates a "stalled" worker
3. observe gc continue to clean up missing containers once the grace-period is up 

## Expected Results

not this. The ATC shouldn't delete container rows when a worker is in stalled state.

## Actual Results

it deletes the row

### PR DESCRIPTION
**Pull request by deniseyu**
* If containers from stalled workers are removed from ATC DB,
  then ATC will be out of sync with worker filesystem when
  worker returns to running state. This contributes to
  problem of mysteriously high container count on workers.

Addresses #4536

Signed-off-by: Denise Yu <dyu@pivotal.io>

# Existing Issue

Fixes #4536.

# Why do we need this PR?

This PR solves one of a few possible edge cases that can contribute to upward-creeping container count on workers. This attempts to keep ATC DB's state closer to the filesystem reality of workers that are flipping between stalled and running state.

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [x] Unit tests
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed

### CODE REVIEW

**Comment by kcmannem** [comment]
lgtm, gonna do the docker test we did during our investigation tomorrow morning and accept this.

File: atc/db/container_repository.go [hunk 1]
```diff
@@ -140,12 +140,20 @@ func (repository *containerRepository) FindDestroyingContainers(workerName strin
 }
 
 func (repository *containerRepository) RemoveMissingContainers(gracePeriod time.Duration) (int, error) {
+	stalledWorkers, err := stalledWorkerNames(repository.conn)
```
Comment (cirocosta) [inline atc/db/container_repository.go]: Heey,

I'm not very familiar with the code under `db`, but I think there's might a rece here given that we're performing those queries within the context of separate transactions - is this right? 

I wonder if this could/should be done in a single sql statement rather than performing a query, loading that in memory, and then using in a separate statement 🤔 

wdyt?

thx!

Comment (deniseyu) [reply atc/db/container_repository.go]: yea, I wanted to implement this as one atomic operation, but the challenge is that you can't do a left-join inside of a DELETE so unfortunately it has to happen in two steps, unless there's something I'm missing from the sparsely-documented sql library we're using...

Comment (cirocosta) [reply atc/db/container_repository.go]: oh, interesting! 

Being that the case, should we use the same transaction for that though? Is that a pattern that we use throught `db`? Or, perhaps, use subqueries (assuming that's permitted)?

thanks!!

Comment (deniseyu) [reply atc/db/container_repository.go]: yea that's a good point! we have a few other places in our codebase, like [here](https://github.com/concourse/concourse/blob/master/atc/db/check.go#L139-L175) where we do multiple stuff within one transaction so it's certainly not a brand new pattern. thanks @cirocosta for the catch 😄

File: atc/db/container_repository.go [hunk 2]
```diff
@@ -140,17 +140,21 @@ func (repository *containerRepository) FindDestroyingContainers(workerName strin
 }
 
 func (repository *containerRepository) RemoveMissingContainers(gracePeriod time.Duration) (int, error) {
-	result, err := psql.Delete("containers").
+	result, err := psql.Delete("containers USING workers").
```
Comment (ddadlani) [inline atc/db/container_repository.go]: inspired by https://github.com/concourse/concourse/blob/ba5a5932f1921fd8c2d22d0246dae2af3a6abd78/atc/db/worker_task_cache.go#L97

File: atc/db/container_repository.go (hunk 1 above)
Comment (ddadlani) [reply atc/db/container_repository.go]: we're using USING instead, inspired by https://github.com/concourse/concourse/blob/ba5a5932f1921fd8c2d22d0246dae2af3a6abd78/atc/db/worker_task_cache.go#L97

**Comment by deniseyu** [comment]
this solution is much cleaner, thanks @ddadlani @kcmannem 🤘  i can't approve this since i opened it, but maybe @xtreme-sameer-vohra can!

i'm still not 100% happy with how those unit tests are written, they're just kind of confusing to read, but they can be iteratively improved later.

**Comment by ddadlani** [comment]
FYI we've left the unit build pending because it's going to fail, once we push another commit fixing tests it should re-trigger

**Comment by xtreme-sameer-vohra** [comment]
@deniseyu & @ddadlani 
With this fix, would a build ( & their corresponding steps ) that was running on a stalled worker, remain stuck in its previous state prior to the worker stalling indefinitely ?

Would that be desired ?

**Comment by ddadlani** [comment]
@xtreme-sameer-vohra build status is not dependent on the existence of a container. The build status should update only if the process running in the container returns a status code. If a worker was stalled while a process is running, the build status would be stuck in its previous state regardless of these changes.

If the worker recovers from the stalled state, GC should kick in and ensure that worker and DB container state are synchronized. If the worker goes away, GC should clean up all the resources on that worker. This PR simply ensures that we don't make any assumptions about the state of resources on a stalled worker, since we don't have enough information.

**Comment by kcmannem** [comment]
Don't merge this pr depends on #3600. I didn't want to add tests and remove tests in the span of 2 hours.

**Comment by xtreme-sameer-vohra** [comment]
> @xtreme-sameer-vohra build status is not dependent on the existence of a container. The build status should update only if the process running in the container returns a status code. If a worker was stalled while a process is running, the build status would be stuck in its previous state regardless of these changes.
> 
> If the worker recovers from the stalled state, GC should kick in and ensure that worker and DB container state are synchronized. If the worker goes away, GC should clean up all the resources on that worker. This PR simply ensures that we don't make any assumptions about the state of resources on a stalled worker, since we don't have enough information.

Yep, that makes sense. Looking at the code https://github.com/concourse/concourse/blob/master/atc/worker/pool.go#L134 for a case where the web that initiated the build went away and another web took over tracking the build, `ContainerInWorker` will filter for `running` workers only.

File: atc/db/container_repository.go (hunk 1 above)
Comment (kcmannem) [reply atc/db/container_repository.go]: Done

File: atc/db/container_repository.go (hunk 2 above)
Comment (kcmannem) [reply atc/db/container_repository.go]: done

**Comment by kcmannem** [comment]
@ddadlani just tested it manually again, it works.
