### PR TITLE
web: fix various dashboard search issues

### LINKED ISSUE #2703: typing a question mark in the dashboard search bar toggles the help menu
it's minor, but if you have the search bar focused on the dashboard and you type `?` a bunch of times, you will be distracted by the rapidly-toggling help menu.

Perhaps a better behaviour would be for the usual keyboard shortcuts to be temporarily disabled while the search bar is focused.

### LINKED ISSUE #3226: Escape key no longer blurs the dashboard search input
## Bug Report

as part of the introduction of the stop-gap `NewestTopBar` module we seem to have mixed up the words 'focus' and 'blur'.

## Steps to Reproduce

1. Have at least one visible pipeline.
1. Visit the dashboard.
1. Focus the search input.
1. hit the Escape key.

## Expected Results

The search input is blurred and the autocomplete dropdown dismisses.

## Actual Results

The search input is still focused and the autocomplete dropdown is still there.

## Additional Context

Looking back a bit, [this](https://github.com/concourse/concourse/commit/50cdabf266a93f30767594813ac2ab7bd953ce66#diff-e15c61fff176e32aa5029ea91a239d87L297) is ultimately the offending change, but we should have tests to protect against this, too.

## Version Info

* Concourse version: 5.0.0 (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? Yes, it works on 4.2.2 on wings.

### LINKED ISSUE #3317: hitting any key on the dashboard causes the autocomplete to appear
## Bug Report

Hitting the keyboard on the dashboard page even without the search input focused causes the  autocomplete dropdown to appear, which is a bit jarring.

## Steps to Reproduce

1. Visit the regular dashboard such that the search appears (i.e. you can see at least one pipeline)
1. Ensure the search input is not focused
1. hit any key on the keyboard (except `/`)

## Expected Results

No visible change.

## Actual Results

The autocomplete dropdown appears.

## Additional Context

Probably an 'integration bug' resulting from moving the `KeyDown` message to the top level - more specifically `Application` seems to 'assume' that all keydowns on the dashboard page 'originate' from the TopBar (i.e. https://github.com/concourse/concourse/blob/62d606ebfd1b0fdf10bd0075767b1b025417912d/web/elm/src/Application/Application.elm#L251), in which case `TopBar` winds up receiving the message and defaults to showing the dropdown (i.e. https://github.com/concourse/concourse/blob/62d606ebfd1b0fdf10bd0075767b1b025417912d/web/elm/src/TopBar/TopBar.elm#L364), which may actually be a bug...

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? yes

### LINKED ISSUE #3353: Concourse dashboard search doesn't autocomplete teams if you're not logged in
## Bug Report

Concourse dashboard search doesn't autocomplete teams if you're not logged in. I started noticing this on the latest Concourse 5.x release on https://ci.concourse-ci.org/

## Steps to Reproduce

1. Go to the dashboard https://ci.concourse-ci.org/
2. Make sure you're not logged in
3. Type 'team: `

## Expected Results

Expected to see the top 10 matching results as per   
screen shot 2019-02-20 at 4 24 35 pm

## Actual Results

No dropdown appeared!

## Additional Context

If you login and then try again, you'll see the autocomplete suggestions

## Version Info

### LINKED ISSUE #3381: Dashboard search dropdown is displaying without styles on Chrome
screen shot 2019-02-25 at 10 33 28 am
When viewing the Dashboard in Google Chrome (Version 72.0.3626.109) the dropdown displays without the UI concourse style inconsistently. 

Sometimes the concourse styled dropdown returns after a mouse event but, the unstyled dropdown returns displaying overtop of the styled dropdown. 
screen shot 2019-02-25 at 10 37 37 am

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
Branched from #3428, please merge it first.

Fixes #3353 
Fixes #3381 
Fixes #3226 
Fixes #3317 
Fixes #2703

### CODE REVIEW

**Comment by pivotal-jamie-klassen** [comment]
I think there's some indelicate handling of the shift key here. If I have multiple tabs open and I'm looking at the dashboard, If i use Command-Shift-] to switch to another tab, then release those three keys and click back to the tab where I was looking at the dashboard, hitting '/' brings up the keyboard help instead of focusing the search input as I'd expect... until I press and release Shift again.

File: web/elm/src/TopBar/TopBar.elm [hunk 1]
```diff
@@ -48,50 +50,49 @@ import UserState exposing (UserState(..))
...
+      , isPinMenuExpanded = False
+      , route = route
+      , groups = []
+      , query =
             case route of
                 Routes.Dashboard { searchType } ->
                     case searchType of
-                        Routes.Normal search ->
-                            SearchBar { query = Maybe.withDefault "" search, dropdown = Hidden }
+                        Routes.Normal Nothing ->
```
Comment (xtreme-james-cooper) [inline web/elm/src/TopBar/TopBar.elm]: You could probably move this query-lookup function to Routes too?

File: web/elm/src/TopBar/TopBar.elm [hunk 2]
```diff
@@ -466,11 +415,11 @@ viewLogin userState model isPaused =
         []
 
 
-showLogin : Model -> Bool
+showLogin : Model r -> Bool
 showLogin model =
-    case model.middleSection of
-        SearchBar _ ->
-            model.screenSize /= Mobile
+    case ( model.screenSize, middleSection model ) of
```
Comment (xtreme-james-cooper) [inline web/elm/src/TopBar/TopBar.elm]: Now that ScreenSize has no arguments, we can replace this with `showLogin model = model.middleSection /= SearchBar || model.screenSize /= mobile`. I think that's marginally clearer.

File: web/elm/src/TopBar/TopBar.elm [hunk 3]
```diff
@@ -536,24 +491,60 @@ viewMiddleSection model =
...
+        Routes.Dashboard { searchType } ->
+            case
+                ( searchType
+                , query
+                , dropdown
+                , screenSize
+                , groups |> List.concatMap .pipelines
+                )
+            of
+                ( _, _, _, _, [] ) ->
```
Comment (xtreme-james-cooper) [inline web/elm/src/TopBar/TopBar.elm]: Ungh this is an ugly case statement. There's got to be a better way to express it... but I can't think of one. Eurgh.

File: web/elm/src/TopBar/TopBar.elm [hunk 4]
```diff
@@ -601,10 +599,9 @@ viewDropdownItems { query, dropdown } model =
                             ]
 
                         "team:" ->
-                            model.teams
-                                |> RemoteData.withDefault []
+                            groups
                                 |> List.take 10
-                                |> List.map (\t -> "team: " ++ t.name)
+                                |> List.map (\g -> "team: " ++ g.teamName)
```
Comment (xtreme-james-cooper) [inline web/elm/src/TopBar/TopBar.elm]: Are groups and teams actually equivalent?

File: web/elm/src/Dashboard/Footer.elm [hunk 5]
```diff
@@ -148,10 +181,20 @@ legend model =
                     , PipelineStatusSucceeded PipelineStatus.Running
                     ]
                 ++ legendSeparator model.screenSize
-                ++ [ toggleView model.highDensity ]
+                ++ [ toggleView (isHighDensity model) ]
         ]
 
 
+isHighDensity : { a | route : Routes.Route } -> Bool
```
Comment (xtreme-james-cooper) [inline web/elm/src/Dashboard/Footer.elm]: Errrrrgh. Duplication of the same function in Dashboard.Dashboard. Possibly this would make sense being moved to Routes and made a Routes.Route -> Bool function?

File: web/elm/src/TopBar/TopBar.elm (hunk 4 above)
Comment (pivotal-jamie-klassen) [reply web/elm/src/TopBar/TopBar.elm]: yeah! groups are actually better, because they're the source of truth for what's on the dashboard, which is conceptually what you're actually filtering. It's this change that fixes #3353.

Comment (xtreme-james-cooper) [reply web/elm/src/TopBar/TopBar.elm]: Good to hear!
