### PR TITLE
 use the configured resolv.conf for containerd

### LINKED ISSUE #5967: containerd containers on Kubernetes can't talk to web
## Summary

`k8s-topgun` test suite is failing.

**Why is the job failing?**
1. [k8s-topgun](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/288) is still failing because of [these two DNS Proxy tests](https://github.com/concourse/concourse/blob/38e7816949904367a7eb51ebf2ceafad3a401ba3/topgun/k8s/dns_proxy_test.go#L98-L107) that run with containerd.

2. The tests turn off the DNS proxy server and expect that containers will be able to reach the web node in the cluster whether it uses the full address `...-web-namespace-svc.cluster.local:8080` or not `...-web-namespace:8080`. The containers currently cannot reach either address without DNS proxy server running.

3. Previously to enable the DNS proxy for guardian and containerd we used `CONCOURSE_GARDEN_DNS_PROXY_ENABLE`

4. Now we use `CONCOURSE_GARDEN_DNS_ENABLE_PROXY` for guardian, and `CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE` for containerd

**So why do the same tests only fail for containerd and not guardian?**
1. In Guardian's case the contents of the resolv.conf of the worker is copied into the container's resolv.conf. 

2. Containerd does not do this although I remember the topic being brought up before and vaguely remember validating making it happen.

**How did it pass for containerd before?**
1. I've tried Helm installing with the image and chart used in the last passing build of k8s-topgun, and the same is true for containerd's resolv.conf behaviour there. I even rerun that last passing [build](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/272), intercepted it and ran the tests according to the ci script and watched the tests fail contrary to CI.

2. I now have no idea how those two tests ever passed before.

**How to fix this?**
1. Implement the same behaviour that Guardian has. When the proxy isn't enabled put the contents of the worker's resolv.conf into the container.

2. Watch out for this red herring that I spent a while on - the concourse/concourse Docker image is built from this Dockerfile in concourse/concourse-docker , and always sets `CONCOURSE_GARDEN_DNS_ENABLE_PROXY` to true. So I thought whether or not you want to have a proxy DNS server, set or not set it in BOSH release or Helm chart, it always runs.  But setting that value to "false" in the chart, which the tests do, does override this. More [here](https://github.com/concourse/concourse/issues/4085#issuecomment-561733322). To validate whether a proxy server is running you can run the following on the worker:

```
apt-get update && apt-get install net-tools
netstat -lunp | grep -w ':53’
```

3. Figure out what to do with the [Dockerfile](https://github.com/concourse/concourse-docker/blob/master/Dockerfile#L11) setting CONCOURSE_GARDEN_DNS_ENABLE_PROXY to true. It was [introduced](https://github.com/concourse/concourse-docker/commit/a729a4293160fae7e2cc32241999b5bd943594da) a few years ago to deal with this [issue](https://github.com/concourse/concourse/issues/1145). Here are [two](https://github.com/cloudfoundry/guardian/issues/42#issuecomment-304295875) [posts](https://github.com/concourse/concourse/issues/1145) talking about solutions. On Friday I had [disabled](https://github.com/concourse/ci/pull/357/files) this for the concourse/dev Dockerfile but that needs to be reconsidered too given that a lot of people may run into problems according to the posts I linked.

## Triaging info

* Concourse version: 38e7816949904367a7eb51ebf2ceafad3a401ba3
* Did this used to work? Apparently, yes - https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/272

### PR DESCRIPTION
**Pull request by YoussB**
The nameserver values could come from manually defined properties
 or the host itself

Revert "k8s topgun: behaviour: skip containerd dns tests"
This reverts commit 0b03e84c5a1109855351787fd74296430efbcc14.

Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>
Co-authored-by: Vikram Yadav <vyadav@pivotal.io>

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?
Feature

closes #5967  .

## Changes proposed by this PR:
The resolv.conf is injected into the containers created by containerd on a worker. The approach is similar to Garden behaviour: https://github.com/cloudfoundry/guardian/blob/ca905e542c224efde27f5c2070ac6c6f9bc37c0c/kawasaki/resolv.go#L30.

When setting the configuration, the priority is given to the configuration provided by the user by setting `concourse_garden_dns_servers` property. If the user doesn't set this property, we use the worker host's dns configuration inside the container.

## Notes to reviewer:
We couldn't run the topgun tests locally so please make sure the topgun tests passed for this PR on CI.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by YoussB** [comment]
Thanks @xtreme-sameer-vohra, we have addressed the comments 😁.

File: worker/runtime/resolvconf_parser.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import (
+	"fmt"
+	"io/ioutil"
+	"regexp"
+	"strings"
+
+	"code.cloudfoundry.org/localip"
+)
+
+// Parse resolve.conf file from the provided path.
```
Comment (xtreme-sameer-vohra) [inline worker/runtime/resolvconf_parser.go:12]: Might also be worth referencing [resolv_compiler](https://github.com/cloudfoundry/guardian/blob/5ccf9693d394774f17a46de240f31b90597bd70f/kawasaki/dns/resolv_compiler.go) so folks can dig into where some of the reasoning comes from.

**Comment by xtreme-sameer-vohra** [comment]
Manual acceptance testing worked after rebasing off master.

However, the Topgun Tests DON'T pass with:

1. Modify k8s topgun task.yml
   ```
    svohra ~/workspace/ci on master [!$]
    $ git diff
    diff --git a/tasks/k8s-topgun.yml b/tasks/k8s-topgun.yml
    index 072d512..f3fbf4a 100644
    --- a/tasks/k8s-topgun.yml
    +++ b/tasks/k8s-topgun.yml
    @@ -7,8 +7,8 @@ image_resource:
    
     params:
       CONCOURSE_CHART_DIR:
    -  CONCOURSE_IMAGE_NAME:
    -  KUBE_CONFIG:
    +  CONCOURSE_IMAGE_NAME: concourse/concourse-dev
    +  KUBE_CONFIG: ((kube_config))
    
     inputs:
     - name: concourse
    ```

1. Execute the task
   ```
   cd concourse
   fly -t ci execute -c ~/workspace/ci/tasks/k8s-topgun.yml -j concourse/k8s-topgun -i concourse=. -m concourse-rc-image=concourse-dev-alpine-image --tag=k8s-topgun
   ```
