### PR TITLE
Scale job badges to fit custom titles of any length

### LINKED ISSUE #9237: Concourse build badge doesn't fit custom titles that are longer than ~7 characters
## Summary

The endpoint that generates an SVG badge for a build (`/api/v1/teams/{team}/pipelines/{pipeline}/badge`) does not scale correctly when using a custom title longer than about 7 characters.

## Steps to reproduce

1. Create a pipeline called `echo-test` in concourse with the following pipeline definition:
```
jobs:
  - name: test
    plan:
      - task: echo-text
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: debian
          run:
            path: /usr/bin/bash
            args:
              - "-c"
              - "echo Hello World"
```
2. Unpause the pipeline.
3. Run a new build of the test job.
4. Enter http://localhost:8080/api/v1/teams/main/pipelines/echo-test/badge?title=reallylongtitle in the browser search bar of your choice.
5. Observe bad badge SVG.

## Expected results

The badge should properly fit the custom label e.g.

Image

## Actual results

The custom title for the badge extends beyond the badge e.g.

Image

## Triaging info

* Concourse version: commit `d8cabcbdb3ec988e517782382d3dfd7bbdb77c21`
* Browser (if applicable):
* Did this used to work? No

### PR DESCRIPTION
**Pull request by analytically**
Badge endpoint now dynamically calculates width for custom titles with length-based padding (12px/6px/0px). Preserves original status section widths and maintains backward compatibility with default badges.

Fixes #9237

### CODE REVIEW

**Comment by analytically** [comment]
screentshot-2025-10-06 at 11 22 25@2x
screentshot-2025-10-06 at 11 22 42@2x

File: atc/api/jobserver/badge_test.go [hunk 1]
```diff
@@ -0,0 +1,251 @@
+package jobserver_test
```
Comment (taylorsilva) [inline atc/api/jobserver/badge_test.go]: Existing tests for the badge endpoint are here: https://github.com/concourse/concourse/blob/97393cea938d4dfb125071b9542b9e151eab4a47/atc/api/jobs_test.go#L533

I think most of your tests here are already covered by the existing tests. Can you move your tests alongside the existing tests for the badge endpoint?

**Review by taylorsilva — CHANGES_REQUESTED** [review]
Existing badge endpoint tests are failing:

```
$ ginkgo -r -p ./atc/api
...
Summarizing 2 Failures:
  [FAIL] Jobs API GET /api/v1/teams/:team_name/pipelines/:pipeline_name/jobs/:job_name/badge when authorized when generates bagde title [It] html escapes title
  /Users/taylor/workspace/concourse/concourse/atc/api/jobs_test.go:644
  [FAIL] Jobs API GET /api/v1/teams/:team_name/pipelines/:pipeline_name/jobs/:job_name/badge when authorized when generates bagde title [It] uses url `title` parameter
  /Users/taylor/workspace/concourse/concourse/atc/api/jobs_test.go:608

Ran 1003 of 1003 Specs in 3.472 seconds
FAIL! -- 1001 Passed | 2 Failed | 0 Pending | 0 Skipped


Ginkgo ran 9 suites in 9.932889291s

There were failures detected in the following suites:
  api ./atc/api
```

**Review by taylorsilva — APPROVED** [review]
LGTM! 

image
image
image
image
image
