### PR TITLE
Return error when a step only contains modifiers

### LINKED ISSUE #5869: Setting a modifier step without a base step causes (non-fatal) panic
## Summary

Setting a pipeline where a job step has a modifier step field (e.g. `attempts`, `on_success`, etc.) but no base step (e.g. `get`, `task`, etc.) causes the ATC to panic (which gets `recover`ed, fortunately).

## Steps to reproduce

```
$ cat pipeline.yml
jobs:
- name: job
  plan:
  - attempts: 1
$ fly -t dev sp -p hope-this-doesnt-panic -c pipeline.yml
jobs:
  job job has been added:
+ name: job
+ plan:
+ - null

apply configuration? [yN]: y
could not reach the Concourse server called dev:

    Put "http://localhost:8080/api/v1/teams/main/pipelines/bad/config": EOF

is the targeted Concourse running? better go catch it lol
```

## Expected results

It fails to set pipeline with a better error message

## Actual results

(in the logs)
```
web_1     | 2020/07/10 13:16:11 http: panic serving 172.23.0.1:33606: runtime error: invalid memory address or nil pointer dereference
web_1     | goroutine 215562 [running]:
web_1     | net/http.(*conn).serve.func1(0xc0007348c0)
web_1     | 	/usr/local/go/src/net/http/server.go:1772 +0x149
web_1     | panic(0x34b4fe0, 0x50ecc90)
web_1     | 	/usr/local/go/src/runtime/panic.go:975 +0x41b
web_1     | github.com/concourse/concourse/atc.StepRecursor.VisitRetry(0x0, 0xc00026b500, 0xc00026b510, 0x0, 0x0, 0xc0007e6680, 0x0, 0x0)
web_1     | 	/src/atc/step_recursor.go:120 +0x6e
web_1     | github.com/concourse/concourse/atc.(*RetryStep).Visit(0xc0007e6680, 0x3e832e0, 0xc0004cb560, 0x0, 0x0)
web_1     | 	/src/atc/steps.go:489 +0x45
web_1     | github.com/concourse/concourse/atc.StepRecursor.VisitDo(0x0, 0xc00026b500, 0xc00026b510, 0x0, 0x0, 0xc0007e66c0, 0x0, 0x0)
web_1     | 	/src/atc/step_recursor.go:80 +0x15a
web_1     | github.com/concourse/concourse/atc.(*DoStep).Visit(0xc0007e66c0, 0x3e832e0, 0xc0004cb530, 0x0, 0x0)
web_1     | 	/src/atc/steps.go:399 +0x45
web_1     | github.com/concourse/concourse/atc/configvalidate.usedResources(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:201 +0x2dd
web_1     | github.com/concourse/concourse/atc/configvalidate.validateResourcesUnused(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:184 +0x7a
web_1     | github.com/concourse/concourse/atc/configvalidate.validateResources(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:144 +0x74a
web_1     | github.com/concourse/concourse/atc/configvalidate.Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:33 +0x1e5
web_1     | github.com/concourse/concourse/atc/api/configserver.(*Server).SaveConfig(0xc0007165a0, 0x3e52ea0, 0xc000950730, 0xc000ca5700)
web_1     | 	/src/atc/api/configserver/save.go:64 +0xe68
web_1     | net/http.HandlerFunc.ServeHTTP(0xc0004c3930, 0x3e52ea0, 0xc000950730, 0xc000ca5700)
web_1     | 	/usr/local/go/src/net/http/server.go:2012 +0x44
web_1     | github.com/felixge/httpsnoop.CaptureMetrics.func1(0x3e52ea0, 0xc000950730)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:30 +0x67
web_1     | github.com/felixge/httpsnoop.CaptureMetricsFn(0x3e518e0, 0xc000431dc0, 0xc0005d69d0, 0x0, 0x0, 0x0)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:81 +0x3d2
web_1     | github.com/felixge/httpsnoop.CaptureMetrics(0x3dfc3c0, 0xc0004c3930, 0x3e518e0, 0xc000431dc0, 0xc000ca5700, 0x0, 0x0, 0x0)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:29 +0xb3
web_1     | github.com/concourse/concourse/atc/metric.MetricsHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x37d72c1, 0xa, 0x3dfc3c0, 0xc0004c3930, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/metric/http.go:25 +0x74
web_1     | github.com/concourse/concourse/atc/api/policychecker.policyCheckingHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x3dfade0, 0xc000716d20, 0x37d72c1, 0xa, 0x0, 0x0, 0x3e518e0, 0xc000431dc0, ...)
web_1     | 	/src/atc/api/policychecker/handler.go:50 +0x316
web_1     | github.com/concourse/concourse/atc/api/auth.checkAuthorizationHandler.ServeHTTP(0x3dfa9e0, 0xc00007c540, 0x3e189a0, 0x5262ef0, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/api/auth/check_authorization_handler.go:39 +0x136
web_1     | github.com/concourse/concourse/atc/wrappa.VersionedHandler.ServeHTTP(0x37d487b, 0x9, 0x3dfa8e0, 0xc000301480, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/wrappa/versioned_handler.go:14 +0xa7
web_1     | github.com/concourse/concourse/atc/api/accessor.(*accessorHandler).ServeHTTP(0xc00064bcb0, 0x3e518e0, 0xc000431dc0, 0xc000ca5600)
web_1     | 	/src/atc/api/accessor/handler.go:109 +0x690
web_1     | github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x2ba
web_1     | net/http.HandlerFunc.ServeHTTP(0xc0000373b0, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/usr/local/go/src/net/http/server.go:2012 +0x44
web_1     | github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc000434f40, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/go/pkg/mod/github.com/bmizerany/pat@v0.0.0-20170815010413-6226ea591a40/mux.go:117 +0x313
web_1     | github.com/concourse/concourse/atc/api/auth.csrfValidationHandler.ServeHTTP(0x3df5940, 0xc000434f40, 0x3e765a0, 0xc0004249a8, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/api/auth/csrf_validation_handler.go:60 +0x60b
web_1     | net/http.(*ServeMux).ServeHTTP(0xc000314840, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/usr/local/go/src/net/http/server.go:2387 +0x1a6
web_1     | github.com/concourse/concourse/atc/api/auth.WebAuthHandler.ServeHTTP(0x3df9520, 0xc000314840, 0x3e765a0, 0xc0004249a8, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/api/auth/web_auth_handler.go:55 +0x300
web_1     | github.com/concourse/concourse/atc/wrappa.SecurityHandler.ServeHTTP(0x34f0fb2, 0x4, 0x3dfa860, 0xc0003e6880, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/wrappa/security_handler.go:17 +0x1af
web_1     | github.com/concourse/concourse/atc/wrappa.LoggerHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x3dfb000, 0xc0003e68a0, 0x3e514a0, 0xc00014b420, 0xc000ca5500)
web_1     | 	/src/atc/wrappa/logger_handler.go:20 +0x2fb
web_1     | net/http.serverHandler.ServeHTTP(0xc00034c380, 0x3e514a0, 0xc00014b420, 0xc000ca5500)
web_1     | 	/usr/local/go/src/net/http/server.go:2807 +0x20f
web_1     | net/http.(*conn).serve(0xc0007348c0, 0x3e596e0, 0xc00058ab40)
web_1     | 	/usr/local/go/src/net/http/server.go:1895 +0x1716
web_1     | created by net/http.(*Server).Serve
web_1     | 	/usr/local/go/src/net/http/server.go:2933 +0x931
```

## Additional context

I suspect this was introduced by #5504, but maybe it was like this before

Also, it's worth noting the panic isn't fatal (i.e. doesn't take down the ATC), since Go recovers from panics in HTTP handlers

## Triaging info

* Concourse version: 6.4.0
* Did this used to work? Probably

### PR DESCRIPTION
**Pull request by taylorsilva**
## What does this PR accomplish?
**Bug Fix** | Feature | Documentation

closes #5869

## Changes proposed by this PR:
A small change to the json parsing logic used when parsing steps in a job plan. Basically adding a bool flag to let us know if a step contains any core step types or not. If none are found then an error is returned.

Now a user will get:
```
$ cat pipeline.yml
jobs:
- name: job
  plan:
  - attempts: 1
$ fly -t dev sp -p hope-this-doesnt-panic -c pipeline.yml
error: error unmarshaling JSON: while decoding JSON: no core step type declared (e.g. get, put, task, etc.)
```

## Notes to reviewer:
If you use an old version of fly you'll only get the error after hitting the API when trying to set the pipeline. If you recompile fly based on this branch then fly will catch the error locally.

**Open question:** The original issue is about a panic. This PR prevents the panic from happening now but there could still be other ways that a `Step` could be constructed with nils. Should we wrap these cases in `recovers`?
This is where the panic happens when you have a step that only contains a `RetryStep`(`attempts`). The `RetryStep.Step` field is nil, resulting in the panic. **What do you think??**
```go
// VisitRetry recurses through to the wrapped step.
func (recursor StepRecursor) VisitRetry(step *RetryStep) error {
	return step.Step.Visit(recursor)
}
```

## Contributor Checklist
- [x] Followed [Code of conduct]♥️, [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Updated [Release notes]

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

File: atc/steps.go [hunk 1]
```diff
@@ -90,6 +91,10 @@ func (step *Step) UnmarshalJSON(data []byte) error {
 		return ErrNoStepConfigured
 	}
 
+	if !coreStepDeclared {
+		return errors.New("no core step type declared (e.g. get, put, task, etc.)")
```
Comment (vito) [inline atc/steps.go:95]: Can we pull this out as an `ErrNoCoreStepDeclared` var? It's just nice to see the error conditions defined somewhere more discoverable rather than inlined.

File: atc/steps.go [hunk 2]
```diff
@@ -126,6 +132,8 @@ func (step Step) MarshalJSON() ([]byte, error) {
 }
 
 // See the note about json tags here: https://golang.org/pkg/encoding/json/#Marshal
+// keys are deleted based on the assumption that the first non-ignorable field
+// on the step struct matches the name of the step (e.g. get, put, on_success, etc.)
```
Comment (aoldershaw) [inline atc/steps.go:136]: Not sure I totally understand this line. This function deletes every field that the step's `struct` defines that is unmarshaled (i.e. isn't ignored using `json:"-"`). I guess the assumption is that the `Key` in `StepPrecedence` is one of the fields that is declared on the `struct`. Though saying "the first non-ignorable field" is a bit misleading I think

Comment (taylorsilva) [reply atc/steps.go:136]: Hmm I'll change this comment.

> function deletes every field that the step's struct defines 

This line confuses me and I can interpret it in two different ways, not sure which one you mean. I'll update the comment, hopefully it'll clear things up!

Comment (taylorsilva) [reply atc/steps.go]: Okay I think I cleared it up! I actually removed the comment and renamed the function instead. I see how my initial comment was misleading. Let me know your thoughts!

Comment (aoldershaw) [reply atc/steps.go]: The changes make sense to me!

File: atc/steps.go [hunk 3]
```diff
@@ -158,13 +167,13 @@ type StepConfig interface {
...
-// steps that wrap other steps (e.g. hooks like `on_success`, `timeout`, etc.)
+// steps that wrap/modify other steps (e.g. hooks like `on_success`, `timeout`, etc.)
 type StepWrapper interface {
 	// Wrap is called during (Step).UnmarshalJSON whenever an 'inner' step is
 	// parsed.
 	//
-	// Modifier step types should implement this by assigning to an internal
-	// field that has a `json:"-"` struct tag.
+	// Modifier step types should implement this by assigning a `json:"-"` tag to
+	// an internal field of type StepConfig in their struct.
```
Comment (vito) [inline atc/steps.go:176]: This re-wording says something different than what was intended. The original statement was that modifiers should implement the `Wrap` method by assigning the given `StepConfig` to a field of the struct, and that same field should have a `json:"-"` tag so that it is ignored during regular unmarshalling.

This comment suggests that the `json:"-"` tag should be added to the field, but doesn't say that the `Wrap` method should assign it (which is arguably the more important part).

Comment (taylorsilva) [reply atc/steps.go]: I reverted the comment to the original one and then made some changes to it. let me know what you think!

File: atc/steps.go [hunk 4]
```diff
@@ -158,13 +167,13 @@ type StepConfig interface {
...
-// steps that wrap other steps (e.g. hooks like `on_success`, `timeout`, etc.)
+// steps that wrap/modify other steps (e.g. hooks like `on_success`, `timeout`, etc.)
 type StepWrapper interface {
 	// Wrap is called during (Step).UnmarshalJSON whenever an 'inner' step is
 	// parsed.
 	//
-	// Modifier step types should implement this by assigning to an internal
-	// field that has a `json:"-"` struct tag.
+	// Modifier step types should implement this function by assigning to an
+	// internal field, that has a `json:"-"` tag, the passed in StepConfig.
```
Comment (vito) [inline atc/steps.go:176]: I think putting 'the passed in StepConfig' all the way end makes this flow a little awkwardly, haha. Sorry for the nitpick. I'm no authority on English so I'll still approve anyway.

Comment (taylorsilva) [reply atc/steps.go:176]: I agree, I think it reads better if we reference the StepConfig earlier. Changed it!
