### PR TITLE
containerd: Mount `/dev/fuse` to privileged containers

### LINKED ISSUE #7096: No /dev/fuse in privileged containers when using containerd
## Summary

When starting a container with "privileged: true" using the guardian backend then /dev/fuse will be available within the container and i am able to use buildah / fuse-usermount / overlayfs within to build other containers.
With the kernel version bug in 7.3.0 i had to switch the backend to containerd to get our pipelines working again and noticed that privileged containers no longer have /dev/fuse availabe and fuse mounts won't work.

## Steps to reproduce

Set CONCOURSE_RUNTIME=containerd
Then start a container like:
- name: testbuild
  plan:
    - get: ubi8-buildah
    - task: testing
      image: ubi8-buildah
      privileged: true # Needed so we can container in a container (run buildah)
      config:
        platform: linux
        params:
          BUILDAH_ISOLATION: chroot
        run:
          path: sh
          args:
            - -exc
            - |
            container=$(buildah from ubi8-buildah)
            buildah run $container ls

## Expected results

Should show a directory listing within the container

## Actual results

buildah / fusermount complains about a non working fuse and a missing /dev/fuse (suggests loading the kernel module which is present on the worker host though)

## Additional context

a simple ls /dev/fuse in the container should be enough for a simple first test. s3fs / sshfs and similar within containers will have the same problem though.

## Triaging info

* Concourse version: 7.3.0
* Browser (if applicable):
* Did this used to work? with guardian backend yes

### PR DESCRIPTION
**Pull request by aoldershaw**
[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR

closes #7096

this is already done for guardian, but missing in our containerd runtime.

note that we already added a cgroup rule for /dev/fuse, but didn't actually mount the device

this logic is the same as in Guardian - see:
* https://github.com/cloudfoundry/guardian/blob/2f945c09a983e47325c314bf1237c31fe5acda62/guardiancmd/command.go#L528
* https://github.com/cloudfoundry/guardian/blob/2f945c09a983e47325c314bf1237c31fe5acda62/guardiancmd/command_linux.go#L229
* https://github.com/cloudfoundry/guardian/blob/2f945c09a983e47325c314bf1237c31fe5acda62/guardiancmd/server.go#L100-L106

### CODE REVIEW

**Comment by FStelzer** [comment]
looks good :)
i tried this version and was able to successfully use fuse in a privileged container again :+1:

File: testflight/devices_test.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+var _ = Describe("Devices", func() {
+	It("mounts the /dev/fuse device to privileged containers", func() {
+		setAndUnpausePipeline("fixtures/devices.yml")
+
+		watch := fly("trigger-job", "-j", inPipeline("check-fuse-privileged"), "-w")
+		Expect(watch).To(gbytes.Say("succeeded"))
+	})
+
+	It("does not mount the /dev/fuse device to unprivileged containers", func() {
```
Comment (muntac) [inline testflight/devices_test.go:17]: I can't seem to find the test for unprivileged containers in the test [logs](https://ci.concourse-ci.org/builds/169184268). The privileged one shows up fine.

Comment (aoldershaw) [reply testflight/devices_test.go:17]: Maybe it just ran faster - they're only logged when the test takes longer than 15 seconds: https://github.com/concourse/ci/blob/bc25c1f71c2e421cfe0e96efca748ce7b4327f3a/tasks/scripts/testflight#L15

**Review by muntac — APPROVED** [review]
LGTM!
