### PR TITLE
topgun/k8s: clean up for worker_lifecycle and reduce case flakiness.

### LINKED ISSUE #3479: Auto-bump golang versions
It would be nice to auto-bump golang versions in both the main concourse pipeline as well as the hotfix pipeline.

### LINKED ISSUE #3749: [topgun/k8s] worker_lifecycle test doesn't clean up when it fails + flakiness
The `worker_lifecycle` test in `k8s-topgun` doesn't clean up after itself. If the test fails then it leaves behind the namespace and pods that it made. If it fails multiple times in a row (like it has recently) then we end up using all the resources in the k8s cluster.

We should fix the test to ensure cleanup is always being done.

### PR DESCRIPTION
**Pull request by cirocosta**
- clean up even when test fails
- added 2 sleeps to reduce the flakiness as temporary solution

fixes #3749

Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>
Co-authored-by: Bin Ju <bju@pivotal.io>

### CODE REVIEW

**Comment by cirocosta** [comment]
whops, the commit message has a `fixes` with the wrong issue number.

File: topgun/k8s/worker_lifecycle_test.go [hunk 1]
```diff
@@ -26,6 +26,12 @@ var _ = Describe("Worker lifecycle", func() {
 		RerunJob                  bool
 	}
 
+	AfterEach(func() {
+		helmDestroy(releaseName)
```
Comment (YoussB) [inline topgun/k8s/worker_lifecycle_test.go]: can we use the cleanup function as we do here: https://github.com/concourse/concourse/blob/master/topgun/k8s/baggageclaim_drivers_test.go#L18-L20

Comment (taylorsilva) [reply topgun/k8s/worker_lifecycle_test.go]: @cirocosta can you make these changes and then I can merge

**Comment by cirocosta** [comment]
Force pushed due to a rebase.

```
• [SLOW TEST:121.218 seconds]
Worker lifecycle
/Users/cirocosta/workspace/concourse/topgun/k8s/worker_lifecycle_test.go:15
  retiring a worker
  /Users/cirocosta/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table.go:92
    gracefully
    /Users/cirocosta/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table_entry.go:46
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
• [SLOW TEST:143.801 seconds]
Worker lifecycle
/Users/cirocosta/workspace/concourse/topgun/k8s/worker_lifecycle_test.go:15
  retiring a worker
  /Users/cirocosta/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table.go:92
    ungracefully
    /Users/cirocosta/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table_entry.go:46
------------------------------

Ran 2 of 27 Specs in 152.590 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 25 Skipped
```

File: topgun/k8s/worker_lifecycle_test.go (hunk 1 above)
Comment (taylorsilva) [reply topgun/k8s/worker_lifecycle_test.go]: Opened issue to remove the sleeps https://github.com/concourse/concourse/issues/3795
