### PR TITLE
Fallback hijack to sh when bash is missing

### LINKED ISSUE #5877: missing bash makes hijack appear to fail
## Summary

```
Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\": unknown","Handle":"","ProcessID":"","Binary":""}
```

## Steps to reproduce

Use @vito buildkit container, or any container which does not contain bash.

## Expected results

Fall back to the default shell sh.

## Actual results

Failure to log in.

## Additional context

`fly -t target hijack -u https://url`
where
`fly -t target hijack -u https://url sh`
works.

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable): Firefox
* Did this used to work? Not sure, I think so far all containers had bash.

### PR DESCRIPTION
**Pull request by shua**
[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | Feature

Fixes  #5877

## Changes proposed by this PR:

The intent of this PR was to allow `fly hijack` commands with no path specified, to assume the user just wants some shell, and if `bash` isn't available, try again with `sh`. This required some changes to atc to unmarshal a `garden.ExecutableNotFoundError` sent from the container, and turning that into a special message sent back to fly.

It feels a little inelegant to pass back another return variable (a `bool`) in a couple places where we already pass an exit status `int`, but I didn't have enough understanding of the exit status codes to feel comfortable just passing back `254`, and figured if golang supports it, another return var is better then some weird edge case where `254` is passed back and the user is unexpectedly re-hijacking with `sh`.

This is based on prior work and suggestions on https://github.com/concourse/concourse/pull/4755

## Release Note

The default behaviour of the `fly hijack` command when a path is not specified was to use `"bash"`. This default behaviour has changed so that it first tries to use `"bash"`, but if the container returns an error indicating bash is not available, `fly` will retry the hijack using more limited but more common `"sh"`. If this fallback logic is not desired, the user can explicitly specify `bash` as the path argument to the `fly hijack` command. 

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

File: fly/integration/hijack_test.go [hunk 1]
```diff
@@ -874,6 +881,50 @@ var _ = Describe("Hijacking", func() {
...
+				flyCmd := exec.Command(flyPath, "-t", targetName, "hijack", "-b", "2", "-s", "some-step")
+
+				stdin, err := flyCmd.StdinPipe()
+				Expect(err).NotTo(HaveOccurred())
+
+				sess, err := gexec.Start(flyCmd, GinkgoWriter, GinkgoWriter)
+				Expect(err).NotTo(HaveOccurred())
+
+				Eventually(hijacked).Should(BeClosed())
+				// Eventually(hijacked2).Should(BeClosed())
```
Comment (shua) [inline fly/integration/hijack_test.go:913]: I don't really understand how these tests work, so my attempts so far at just copy-pasting things around has only gotten me so far. This test is currently failing because one of the `hijackHandler` mocks is expecting `"some stdin"` but just getting a closed stdin. If I add a second line of
```golang
fmt.Fprintf(stdin, "some stdin")
```
then the test with expecting `"some stdin"` but getting `"some stdinsome stdin"`.

I am pretty stumped on how to resolve this...

File: fly/integration/hijack_test.go [hunk 2]
```diff
@@ -1045,4 +1047,95 @@ var _ = Describe("Hijacking", func() {
...
+				os.Stdout.WriteString(fmt.Sprintf("ABOUT TO CHECK HIJACKED2: %v\n", hijacked2))
+				Eventually(hijacked2).Should(BeClosed())
+
+				os.Stdout.WriteString("ABOUT TO PUT TO STDIN\n")
+				_, err = fmt.Fprintf(stdin, "some stdin")
+				Expect(err).NotTo(HaveOccurred())
+				_, err = fmt.Fprintf(stdin, "some stdin")
+				Expect(err).NotTo(HaveOccurred())
+
+				err = stdin.Close()
```
Comment (shua) [inline fly/integration/hijack_test.go:1129]: for some reason this goes through, and the two writes of `"some stdin"` are not?
```
ABOUT TO CLOSE DIDHIJACK: 0xc0006f6060
ABOUT TO READ PROCSPEC
ABOUT TO READ INPUT
ABOUT TO CHECK HIJACKED2: 0xc0006f6060
ABOUT TO PUT TO STDIN
ABOUT TO CHECK STDOUT STDERR
ABOUT TO PARSE INPUT
logging in to team 'main'


target saved
executable not found
Couldn't find "bash" on container, retrying with "sh"

------------------------------
• Failure [0.071 seconds]
Hijacking
/home/shua/src/concourse/fly/integration/hijack_test.go:19
  when hijacking yields an executable not found error
  /home/shua/src/concourse/fly/integration/hijack_test.go:1051
    when a path was not specified
    /home/shua/src/concourse/fly/integration/hijack_test.go:1101
      tries "bash" then "sh" [It]
      /home/shua/src/concourse/fly/integration/hijack_test.go:1105

      Expected
          <atc.HijackInput>: {Closed: true, Stdin: nil, TTYSpec: nil}
      to equal
          <atc.HijackInput>: {Closed: false, Stdin: "some stdin", TTYSpec: nil}

      /home/shua/src/concourse/fly/integration/hijack_test.go:65
```

If I remove this line, then the test fails in the following way. Notice that no `ABOUT TO WRITE STDOUT STDERR` message, which indicates atc side is still waiting on reading input from `conn` even though I've printed a bunch of stuff to `stdin`.
```
ABOUT TO CLOSE DIDHIJACK: 0xc0009b8060
ABOUT TO READ PROCSPEC
ABOUT TO READ INPUT
ABOUT TO CHECK HIJACKED2: 0xc0009b8060
ABOUT TO PUT TO STDIN
ABOUT TO CHECK STDOUT STDERR
logging in to team 'main'


target saved
executable not found
Couldn't find "bash" on container, retrying with "sh"

------------------------------
• Failure [10.072 seconds]
Hijacking
/home/shua/src/concourse/fly/integration/hijack_test.go:19
  when hijacking yields an executable not found error
  /home/shua/src/concourse/fly/integration/hijack_test.go:1051
    when a path was not specified
    /home/shua/src/concourse/fly/integration/hijack_test.go:1101
      tries "bash" then "sh" [It]
      /home/shua/src/concourse/fly/integration/hijack_test.go:1105

      Timed out after 10.000s.
      Got stuck at:
          
      Waiting for:
          some stdout

      /home/shua/src/concourse/fly/integration/hijack_test.go:1130
```

**Review by shua — COMMENTED** [review]
if the reviewer could help me out with this int testing framework, it'd be much appreciated. The feature works as expected with manual testing, but I'm having trouble writing these automated tests.

File: fly/integration/hijack_test.go (hunk 2 above)
Comment (shua) [reply fly/integration/hijack_test.go:1129]: @zoetian any pointers for me?

Comment (aoldershaw) [reply fly/integration/hijack_test.go:1129]: Hey @shua, sorry for the delay. @zoetian and I looked into this today, and think we've found the issue.

The `Hijacker` spawns a goroutine that runs `io.Copy` from `pio.In` (stdin of the `fly` process) to a custom `io.Writer` that emits read bytes as `HijackInput` messages.

https://github.com/concourse/concourse/blob/6bdcad882dcb28b9c56a5be16ce31b173804f907/fly/commands/internal/hijacker/hijacker.go#L72-L75

You call `Hijack` twice (once for `bash`, and then once for `sh`), so the goroutine from when we tried to hijack with `bash` is still alive when we start hijacking `sh`. When you write to stdin in the test, it appears to get read in that first goroutine - and since it's already been read, the goroutine for `sh` doesn't see the data.

It'd be nice to cancel the first `io.Copy`, but readers don't support cancelation. We thought of an alternative approach - handle reading stdin outside of the `Hijacker`, feed the result into a `chan atc.HijackInput`, and pass that `chan` into the `Hijacker` in place of `ProcessIO.In`.

You'd also want to pass in a `context.Context` to `Hijacker.Hijack`, and add a `case <-ctx.Done()` to https://github.com/concourse/concourse/blob/6bdcad882dcb28b9c56a5be16ce31b173804f907/fly/commands/internal/hijacker/hijacker.go#L141-L147 (to prevent draining the input chan).

So, `fly/commands/hijack.go` could look something like:

```go
		...
		inputs := make(chan atc.HijackInput, 1)
		go func() {
			var buf [1024]byte
			for {
				n, err := in.Read(buf[:])
				if err != nil {
					break
				}
				inputs <- atc.HijackInput{Stdin: buf[:n]}
			}
			inputs <- atc.HijackInput{Closed: true}
		}()
		io := hijacker.ProcessIO{
			In:  inputs,
			Out: os.Stdout,
			Err: os.Stderr,
		}

		ctx := context.Background()
		h := hijacker.New(target.TLSConfig(), reqGenerator, target.Token())
		result, exeNotFound, err := h.Hijack(ctx, team.Name(), chosenContainer.ID, spec, io)

		if exeNotFound && someShell {
			spec.Path = "sh"
			os.Stderr.WriteString("\rCouldn't find \"bash\" on container, retrying with \"sh\"\n\r")
			result, exeNotFound, err = h.Hijack(ctx, team.Name(), chosenContainer.ID, spec, io)
		}
		return result, err
	}()
	...
```

And `fly/commands/internal/hijacker/hijacker.go` could look like:

```go
type ProcessIO struct {
	In  <-chan atc.HijackInput
	Out io.Writer
	Err io.Writer
}

func (h *Hijacker) Hijack(ctx context.Context, teamName, handle string, spec atc.HijackProcessSpec, pio ProcessIO) (int, bool, error) {
	...
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	go h.monitorTTYSize(ctx, inputs) // handles <-ctx.Done()
	go h.handleInput(ctx, conn, inputs) // handles <-ctx.Done()

	exitStatus, exeNotFound := h.handleOutput(conn, pio)

	return exitStatus, exeNotFound, nil
}
```

---

Let me know if this doesn't make sense/if you have a better approach in mind!

Comment (shua) [reply fly/integration/hijack_test.go:1129]: thanks for the pointers, I'll try to dig into your suggestions a little and hopefully have an update for this PR sometime this week

**Review by aoldershaw — APPROVED** [review]
Looks good to me! Thanks for making the changes. Things work as I would expect (without specifying an executable, it does the fallback behaviour, but specifying `bash` explicitly, it doesn't try `sh`).

**Comment by shua** [comment]
just realized I wrote a note in the git review, but didn't know I was supposed to add release notes to a file in the repo. Oh well :shrug: hope it isn't an issue. Thanks for the help @aoldershaw and @zoetian!

**Comment by aoldershaw** [comment]
@shua we used to add release notes to a file in the repo, but now the release note is driven from the PR description, so you're all good! Thanks again for the contribution!
