### PR TITLE
atc/worker: fix limit-active-tasks

### LINKED ISSUE #6356: limit active tasks no longer waits when workers are busy
## Summary

In #6339 two new container placement strategies were added. A new error path was also added and this now overrides the waiting behaviour that was added by the `limit-active-tasks` strategy. Instead of waiting for a worker to become available the build errors with the error message from #6339

## Steps to reproduce

Select the limit active tasks placement strategy:
```
CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: "limit-active-tasks"
CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER: 1
```

Set a pipeline, start a build, wait for the task to be running and then start a second build of the same job:

```
fly -t dev sp -p test -c ./topgun/pipelines/task-waiting.yml
fly -t dev up -p test
```

## Expected results

Second build waits for a worker to become available.

## Actual results

Second build errors with `no worker fit container placement strategy: limit-active-tasks`

## Triaging info

* Concourse version: As of a851d623b0cf4ea705ad3d3fa3af755b8a9627b2
* Browser (if applicable):
* Did this used to work? yes

### PR DESCRIPTION
**Pull request by taylorsilva**
## What does this PR accomplish?
**Bug Fix** | Feature | Documentation

closes #6356

Limit active tasks is supposed to wait for a worker to become available.
This broke in #6339. This commit fixes it when limit-active-tasks is one
of the placement strategies.

Also added a test to ensure the waiting for worker path is executed.

I tried to modify the code so all strategies would wait for workers but
I think this kind of waiting needs to happen in the worker.pool which
would break the metrics for limit-active-tasks which happens in
worker.client.chooseTaskWorker().

## Notes to reviewer:
Follow the reproducible steps in #6356 for acceptance.

Release notes are not needed. This is fixing a bug in an unreleased feature (#6339).

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] ~Updated [Documentation]~
- [ ] ~Added release note (Optional)~

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

File: atc/worker/client.go [hunk 1]
```diff
@@ -621,7 +621,9 @@ func (client *client) chooseTaskWorker(
 			workerSpec,
 			strategy,
 		); err != nil {
-			return nil, err
+			if _, ok := err.(NoWorkerFitContainerPlacementStrategyError); !ok {
+				return nil, err
+			}
 		}
 
 		if !strategy.ModifiesActiveTasks() {
```
Comment (evanchaoli) [inline atc/worker/client.go:629]: When `NoWorkerFitContainerPlacementStrategyError` occurs, it won't break, but `chosenWorker` is nil, so this check should change to `if chosenWorker != nil && !strategy.ModifiesActiveTasks()`.

**Review by muntac — APPROVED** [review]
LGTM!
